mission-apprentissage/flux-retour-cfas

- server/package.json
- server/src/common/apis/apiReferentielMna.js
- server/src/jobs/seed/seedReferentielSiretUai.js
CRON dans l'infra : https://github.com/mission-apprentissage/flux-retour-cfas-infra/pull/170
> feat: create referentiel siret-uai collection

- server/src/common/apis/apiLba.js
- server/src/common/components/cfas.js
- server/src/common/components/formations.js
- server/src/common/factory/formation.js
Solves https://github.com/mission-apprentissage/flux-retour-cfas/issues/2005
> Optimiser les appels à l'api lba #2005

- server/config/index.js
- server/package.json
- server/src/common/apis/apiTdbMna.js
- server/src/common/components/partageSimplifieUsers.js
- server/src/common/constants/jobsConstants.js
- server/src/jobs/_partage-simplifie/cli.js
- server/src/jobs/_partage-simplifie/send-dossiersApprenants/index.js
- server/src/jobs/_partage-simplifie/users/create/index.js
- server/src/jobs/_partage-simplifie/users/generate-password-update-token/index.js
- server/yarn.lock
Dépends de https://github.com/mission-apprentissage/flux-retour-cfas/pull/2097
Intégration des jobs (cli)
> partage-simplifie: integrate server jobs

- server/migrate-mongo-config.js
Fix (oubli lors de la migration ESM) pour use de dotEnv dans les migrations
> fix(server): migate-mongo using dotEnv

- ui/components/AlertMessage/AlertMessage.jsx
- ui/components/UserWrapper/UserWrapper.jsx
- ui/hooks/useMaintenanceMessages.js
- ui/pages/_app.jsx
- ui/pages/admin/maintenance.jsx
- ui/pages/en-maintenance.jsx
cf https://github.com/mission-apprentissage/flux-retour-cfas/pull/2313
> feat: ajout page /en-maintenance 

- server/src/jobs/seed/start/index.js
petite PR pour ajouter le champ manquant siret dans les données de test
> fix: ajout champ manquant siret dans les données de test

- server/package.json
- server/tests/data/randomizedSample.js
- server/tests/integration/common/actions/formations.actions.test.js
- server/tests/integration/http/dossiersApprenants.route.legacy.test.js
- server/tests/integration/http/maintenances.route.test.js
- server/tests/recette/jobs/send-dossiers-apprenants/index.js
- server/tests/utils/api.js
- ui/pages/reinscription.jsx
A PR to temporary fix the CI by fixing, or skipping, broken tests, until develop is stabilized.
> fix: temporary fix the CI by fixing or skipping broken tests

- server/src/http/routes/admin.routes/maintenances.routes.js
- server/tests/integration/http/maintenances.route.test.js
A small PR to fix a bug preventing admin to disable maintenance messages
> fix admin should be able to disable maintenance messages

- ui/components/Page/components/Footer.jsx
- ui/components/legal/Cgu.jsx
> fix: fix 2 typos in cgu and footer

- server/src/jobs/patches/refacto-migration/rerun-engine/rerun-engine.effectifs.js
Fix du job, j'avais une Heap Out of Memory Error (reproduit en local) car requete sur un trop grand nb de dossiers.
Je split par Organisme_id.
J'ai modifié les logs et supprimé le loadingbar.
Testé en local ✅
> chore: fix reRunEffectifs : split by of & log update

- reverse_proxy/app/nginx/templates/includes/location_api.conf.template
- server/src/jobs/patches/refacto-migration/rerun-engine/rerun-engine.effectifs.js
- server/tests/data/randomizedSample.js
- Fixes des tests unitaires + linter
> chore: fixes tests unitaires

- server/src/common/constants/erpsConstants.js
- server/src/common/model/json-schema/adresseSchema.js
- server/src/common/model/next.toKeep.models/organismes.model.js
- server/src/http/routes/specific.routes/serp.routes/upload.routes.js
- server/src/jobs/seed/start/index.js
- ui/common/constants/erps.js
- ui/components/Page/components/NavigationMenu.jsx
- ui/modules/mon-espace/effectifs/ChoixTransmission.jsx
- ui/modules/mon-espace/effectifs/ConfigurationAPI.jsx
- ui/modules/mon-espace/effectifs/EffectifsPage.jsx
- ui/modules/mon-espace/effectifs/TransmissionAPI.jsx
- ui/modules/mon-espace/effectifs/engine/Effectifs.jsx
- ui/modules/mon-espace/landing/LandingOrganisme/components/OrganismeInfo.jsx
- ui/modules/mon-espace/parametres/OrganismeContributors.jsx
- ui/pages/mon-espace/[part]/effectifs-configuration-erp.jsx
- ui/theme/theme-beta.js
Cette PR permet à un OF de choisir son ERP, et de télécharger le guide d'installation associé. 
Video: https://www.youtube.com/watch?v=9wO-nA6JjH4
**Note:** 
- Formasup n'a pas de fichier d'installation. 
- la PR est fonctionnel, mais il y aura certainement une 2eme passe a faire dessus, une fois le workflow finalisé
> feat: un organisme peut configurer l'ERP utilisé

- server/src/jobs/fiabilisation/uai-siret/create-fiabilisation-uai-siret-mapping/index.js
Fix du job de création de la table de mapping fiabilisation en utilisant l'API du référentiel au lieu de la collection legacy
> fix(server): create fiabilisation mapping using referentiel api

- .infra/ansible/roles/setup/files/app/tools/cron-data-jobs/run-daily-jobs.sh
- server/src/jobs/hydrate/organismes/hydrate-organismes-and-formations.js
- ui/components/Page/components/Footer.jsx
- Ajout de l'update d'un OF via appel API Entreprise dans l'hydrate organismes and formations.
- Ajout du lancement du job dans le CRON quotidien
- Fix de la date dans le footer
> chore: add call api entreprise & update fields in hydrate-organismes

- server/src/common/actions/permissions.actions.js
- server/src/common/services/mailer/emails/activation_user.mjml.ejs
- server/src/common/services/mailer/emails/templates.js
- ui/common/constants/navigationPages.js
- ui/modules/auth/connexion/Connexion.jsx
- ui/modules/auth/inscription/Inscription.jsx
- ui/modules/auth/inscription/InscriptionPilot.jsx
- ui/modules/mon-espace/effectifs/Televersements.jsx
- ui/pages/auth/finalisation.jsx
- ui/pages/auth/modifier-mot-de-passe.jsx
2eme PR pour fixer des bugs / typos mineurs dans la UI
> chore: fix bugs mineurs dans la UI

- DEV.md
- server/src/common/actions/users.actions.js
- server/src/common/services/mailer/emails/activation_user.mjml.ejs
- server/src/common/services/mailer/emails/validation_first_organisme_user_by_tdb_team.mjml.ejs
- server/src/common/services/mailer/emails/validation_user_by_orga_admin.mjml.ejs
- server/src/common/services/mailer/emails/validation_user_by_tdb_team.mjml.ejs
- ui/common/utils/stringUtils.js
- ui/hooks/useEspace.js
- ui/jsconfig.json
- ui/modules/auth/inscription/Inscription.jsx
- ui/modules/auth/inscription/components/InformationBlock.jsx
- ui/modules/mon-espace/effectifs/ChoixTransmission.jsx
- ui/modules/mon-espace/effectifs/Televersements.jsx
- ui/modules/mon-espace/effectifs/engine/EffectifsTable.jsx
- ui/pages/auth/connexion.jsx
- ui/pages/auth/finalisation.jsx
- ui/pages/auth/inscription.jsx
- ui/pages/auth/modifier-mot-de-passe.jsx
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2426
> fix: divers bugs

- .infra/ansible/roles/setup/files/app/tools/cron-data-jobs/run-daily-jobs.sh
Désactivation des 2 jobs CRON (temporaire)
> chore: desactivate daily jobs

- docker-compose.yml
Proposition d'ajout d'une mem limit pour le container redis à 512M.
> chore: add redis memlimit

- .infra/ansible/roles/setup/tasks/configure-backup.yml
- .infra/ansible/roles/setup/tasks/create-cron.yml
- .infra/ansible/roles/setup/tasks/generate-ssl-certificate.yml
Petite PR d'optim infra : rename des CRON avec le timing dans le nom et log dans un fichier dédié
> chore(infra): update des nom des CRON et update fichier de log

- .infra/ansible/roles/setup/files/app/.overrides/common/docker-compose.common.yml
J'ai un bug bizarre sur MB impossible de voir la collection organismes.
En espérant que l'upgrade fasse qqchose 🙏🏼 ...
> chore: upgrade MB

- server/src/http/routes/specific.routes/old/effectifs-apprenants.route.js
Fix & gestion de la route effectifs-apprenants (RCO).
Pour le moment je propose de renvoyer une 503 avec un message.
J'ai modifié en anticipation, l'appel à isJobInAction qui n'avait pas été corrigé suite à la suppression du composant jobEvents.
> chore(server): effectifApprenants route temp 503

- server/src/common/actions/effectifs.actions.js
Il y a des cas ou le validationErrors était null, j'ai mis une valeur défault []
> fix(server): add default value for validationErrors on updateEffectifsAndLock

- ui/modules/mon-espace/effectifs/engine/Effectifs.jsx
- ui/modules/mon-espace/landing/LandingOrganisme/components/OrganismeInfo.jsx
Une PR à déployer demain matin en prod pour afficher un petit message d'information sur l'import de fichier. J'ai dupliqué le code parce qu'il n'est pas censé rester longtemps en place
> feat: add add warning on home page and import page

- .github/workflows/release-production.yml
- .infra/ansible/env.ini
maintenant que nous mergeons direct dans master, PR pour appeler le workflow `Release version production` a la mano
> chore: release production on workflow_dispatch

- server/package.json
- server/src/common/actions/engine/engine.actions.js
- server/src/common/actions/infoSiret.actions.js
- server/src/common/actions/sifa.actions/sifa.actions.js
- server/src/common/apis/ApiCfaDock.js
- server/src/common/apis/ApiEntreprise.js
- server/src/common/apis/apiCatalogueMna.js
- server/src/common/apis/apiTablesCorrespondances.js
- server/src/common/utils/adresseUtils.js
- server/src/common/utils/validationUtils.js
- server/src/config.js
- server/src/http/routes/specific.routes/effectif.routes.js
- server/src/http/server.js
- server/src/jobs/_toRemove/seedFormations.js
- server/src/jobs/hydrate/_toRemove/formations/hydrate-formations-from-dossiersApprenants.js
- server/tests/data/randomizedSample.js
- server/tests/integration/common/actions/formations.actions.test.js
- server/tests/integration/http/dossiersApprenants.route.legacy.test.js
- server/tests/integration/http/indicateurs.route.test.js
- server/tests/utils/nockApis/nock-Lba.js
- server/tests/utils/nockApis/nock-apiCatalogue.js
- server/tests/utils/nockApis/nock-apiEntreprise.js
- server/tests/utils/nockApis/nock-tablesCorrespondances.js
cette PR remet en place les tests désactivés il y a quelques semaines
> fix: tests dossier apprenants

- Makefile
- server/src/common/actions/infoSiret.actions.js
- server/src/common/actions/organismes/organismes.actions.js
- server/src/jobs/scriptWrapper.js
- ui/components/Breadcrumb/Breadcrumb.jsx
- ui/components/Profile/ProfileInformation.jsx
- ui/components/Ribbons/RibbonsOrganismeNotFound.jsx
- ui/components/Ribbons/RibbonsUnauthorizedAccessToOrganisme.jsx
- ui/components/UserWrapper/UserWrapper.jsx
- ui/hooks/useEspace.js
- ui/hooks/useOrganisme.js
- ui/modules/mon-espace/effectifs/ChoixTransmission.jsx
- ui/modules/mon-espace/effectifs/engine/TransmissionFichier/components/UploadFiles.js
- ui/modules/mon-espace/effectifs/engine/cerfaForm/CerfaForm.js
- ui/modules/mon-espace/effectifs/engine/cerfaForm/blocks/apprenant/EffectifApprenant.js
- ui/modules/mon-espace/effectifs/engine/cerfaForm/blocks/contrats/EffectifContrats.js
- ui/modules/mon-espace/effectifs/engine/cerfaForm/blocks/statuts/EffectifStatuts.js
- ui/modules/mon-espace/effectifs/engine/hooks/useDossier.js
- ui/modules/mon-espace/effectifs/engine/services/api.service.js
- ui/pages/admin/roles.jsx
- ui/pages/admin/users.jsx
- ui/pages/mon-espace/mes-organismes.jsx
PR dédiée pour qq fixes que je trainent dans une PR plus grosse (split de la page part/slug).
> fix: fixe de quelques bugs mineurs

- .infra/ansible/roles/setup/files/app/.overrides/dev/docker-compose.env.yml
- .infra/ansible/roles/setup/files/app/.overrides/production/docker-compose.env.yml
- .infra/ansible/roles/setup/files/app/.overrides/recette/docker-compose.env.yml
- docker-compose.override.yml
- docker-compose.yml
- server/src/http/server.js
- ui/sentry.init.js
+ un fix pour enabler sentry sur la UI
> chore: enable sentry on production

- server/Dockerfile
- server/Dockerfile.dev
Petit problème de build du server en dev qui ne passe pas. (On devrait tester le build de l'image en CI !)
> fix: server Dockerfile{,.dev} syntax

- scripts/preventSensibleFilesCommit.sh
- server/tests/data/entreprise.api.gouv.fr/entreprises/414610212.json
- server/tests/data/entreprise.api.gouv.fr/entreprises/775680135.json
- server/tests/data/entreprise.api.gouv.fr/entreprises/779378272.json
- server/tests/data/entreprise.api.gouv.fr/entreprises/783543614.json
- server/tests/data/entreprise.api.gouv.fr/etablissements/41461021200014.json
- server/tests/data/entreprise.api.gouv.fr/etablissements/77568013501089.json
- server/tests/data/entreprise.api.gouv.fr/etablissements/77568013501139.json
- server/tests/data/entreprise.api.gouv.fr/etablissements/77937827200016.json
- server/tests/data/entreprise.api.gouv.fr/etablissements/78354361400029.json
- server/tests/integration/http/dossiersApprenants.route.legacy.test.js
- server/tests/utils/nockApis/index.js
- server/tests/utils/nockApis/nock-apiCatalogue.js
- server/tests/utils/nockApis/nock-apiEntreprise.js
cette PR ameliore un peu le framework de tests: 
- l'api entreprise est maintenant tout le temps nocker
- et elle utilise de la donnée réelle
> feat: use real data to nock entreprise.api.gouv.fr

- server/src/common/services/mailer/mailer.js
https://github.com/orgs/mission-apprentissage/projects/7/views/2?filterQuery=support+&pane=issue&itemId=20073485
> chore: maj email no-reply pour tableau-de-bord@apprentissage.beta.gouv.fr

- .infra/ansible/roles/deploy/tasks/main.yml
following https://github.com/mission-apprentissage/flux-retour-cfas/pull/2556
> fix: installe pip sur le server pour ajout pwd sur mailhog

- ui/modules/mon-espace/effectifs/Televersements.jsx
- ui/modules/mon-espace/effectifs/engine/TransmissionFichier/hooks/useDocuments.js
> fix: corrige une requête en erreur sur la page téléversement

- .github/workflows/release-production.yml
j'en ai aussi profité pour lancer les tests avant de faire le changement de version
> chore: déploiement en production depuis gh actions

- ui/modules/mon-espace/parametres/OrganismeContributors.jsx
un petit fix pour afficher les users sans organisations
> fix: liste des utilisateurs invités sans organisation

- ui/pages/admin/users.jsx
l'erreur 409 remontée dans [cette issue](https://github.com/mission-apprentissage/flux-retour-cfas/issues/2491) a deja été fixée, et cette PR rajoute en plus le scroll jusqu'a l'utilisateur fraichement crée.
> fix: focus sur l'utilisateur crée

- .github/workflows/_deploy.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/cron-recette.yml
- .github/workflows/release-production.yml
- .github/workflows/release-recette.yml
pour fixer les warnings suivants:
> chore: upgrade des gh action steps

- server/src/common/constants/territoiresConstants.js
- server/src/common/services/mailer/emails/templates.js
- server/src/common/services/mailer/emails/validation_user_by_tdb_team.mjml.ejs
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2430
et voici les emails dans les 3 cas:
> feat: affichage des régions dans l'email de validation de l'admin

- server/src/http/routes/user.routes/password.routes.js
- ui/components/UserWrapper/UserWrapper.jsx
- ui/pages/auth/mot-de-passe-oublie.jsx
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2581
> fix: mot de passe perdu devrait etre case insensitive

- server/migrations/20230206153259-drop-useless-collections.js
- server/src/common/mongodb.js
Vérification de l'existence des collections avant de les drop.
> fix(server): migration drop useless collection if exists

- server/src/common/actions/organismes/organismes.actions.js
- ui/components/Breadcrumb/Breadcrumb.jsx
- ui/hooks/useOrganisme.js
- ui/modules/mon-espace/effectifs/ChoixTransmission.jsx
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2607
> fix: fix les liens ERPS qui sont cassés

- server/src/common/actions/organismes/organismes.actions.js
- server/src/common/actions/users.afterCreate.actions.js
- server/src/http/routes/user.routes/register.routes.js
Des petites corrections pour récupérer un organisme via son SIRET en plus de l'UAI lors de la finalisation de l'inscription (demande d'accès).
> fix: correction de bugs liés à l'UAI manquant à la finalisation des comptes

- server/src/jobs/cli.js
- server/src/jobs/patches/remove-organismes-sansSiret-sansEffectifs/index.js
Script "patch" pour supprimer des organismes qui n'ont plus sens à etre dans le tdb
> chore(server): ajout d'un script de suppression des organismes sans siret & sans effectifs

- ui/.gitignore
- ui/.storybook/main.js
- ui/.storybook/preview.js
- ui/.storybook/utils.js
- ui/package.json
- ui/stories/components/AlertMessage.stories.jsx
- ui/stories/components/ContactSection.stories.jsx
- ui/stories/modules/Televersements.stories.jsx
- ui/stories/pages/404.stories.jsx
- ui/stories/pages/auth/en-attente-confirmation.stories.jsx
- ui/stories/pages/auth/finalisation.stories.jsx
- ui/stories/pages/auth/inscription.stories.jsx
- ui/stories/pages/auth/modifier-mot-de-passe.stories.jsx
- ui/stories/pages/auth/mot-de-passe-oublie.stories.jsx
- ui/yarn.lock
C'est assez compliqué d'afficher la page `/auth/finalisation` dans les différents états. Du coup, cette PR introduit storybook, avec quelques exemples pour illustrer le mocking de auth et de react-query, et surtout la page finalisation avec tous les états.
Ca permettra aussi de partager plus facilement ce qui est actuellement déployé.
Pour la demo, c pas là: https://storybook-tdb.vercel.app/
> feat(ui): ajout de storybook

- ui/pages/auth/modifier-mot-de-passe.jsx
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2617
> fix(ui): remplace email support-contrat par tableau-de-bord

- server/migrations/20230228000000-remove-reseau-cci.js
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2613
> fix: script de migration pour supprimer le reseau CCI des organismes

- .github/workflows/_deploy.yml
- server/package.json
- server/src/common/logger.js
- server/src/config.js
- server/yarn.lock
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2618
> feat: notification slack apres deploiement

- server/src/common/actions/legacy/users.legacy.actions.js
- server/src/common/model/users.model.js
- server/tests/integration/common/actions/users.legacy.actions.test.js
Ajout du champ user.last_connection pour tracker qui se connecte encore avec l'ancienne API
> feat: ajout champ user.last_connection

- ui/next-env.d.ts
- ui/next.config.js
- ui/package.json
- ui/pages/_app.tsx
- ui/tsconfig.json
- ui/yarn.lock
cette PR met à jour next pour profiter d'une nouvelle fonctionnalité qui permet de tester si tous les liens sont valides au moment du build.
https://nextjs.org/blog/next-13-2#statically-typed-links
> chore: next 13.2.1

- ui/common/utils/stringUtils.js
- ui/components/IndicateursGridStack.jsx
- ui/components/RepartitionEffectifsTabs/RepartitionEffectifsTabs.jsx
- ui/components/TerritoireFilter/TerritoireFilter.jsx
- ui/components/TerritoireFilter/TerritoireList.jsx
- ui/modules/mon-espace/landing/visualiser-les-indicateurs/IndicateursGridStack.jsx
- ui/modules/mon-espace/landing/visualiser-les-indicateurs/par-organisme/sections/repartition-effectifs/IndicateursAndRepartionCfaNiveauAnneesSection.jsx
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2347#issuecomment-1450210087
> fix: corrections mineures liées aux filtres indicateurs

- ui/modules/mon-espace/effectifs/engine/EffectifsTable.jsx
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2562
> chore: mise à jour du label du champs source

- server/migrations/20230313000000-fix-wrong-organisme-no-uai.js
- server/src/common/actions/organismes/organismes.actions.js
- server/src/common/actions/users.actions.js
- server/src/common/actions/users.afterCreate.actions.js
- server/src/http/routes/user.routes/register.routes.js
- server/src/jobs/seed/start/index.js
- server/tests/integration/http/indicateurs.route.test.js
Corrige #2714 
Il me reste à voir la correction des données existantes via une migration
> fix: corrige la mauvaise association à l'organisme si pas d'UAI

- server/src/jobs/fiabilisation/uai-siret/apply-fiabilisation/index.js
Ajout au script de fiabilisation d'un traitement de correction des organismes marqués comme NON_FIABILISABLE_MAPPING.
On va cherche un unique organisme FIABLE lié à cet organisme NON_FIABILISABLE_MAPPING et déplacer tous ses effectifs non déja présents (sujet doublon en pilotage via MB) sur le bon organisme FIABLE.
La volumétrie n'est pas très conséquente.
NB : Une autre PR viendra ajouter un script de clean qui va "supprimer" les effectifs NON_FIABILISABLE_MAPPING une fois la correction d'effectif faite.
> fix(server): rapatriement des effectifs sur organismes fiable depuis organismes non fiabilisable mapping

- ui/components/Page/components/Footer.jsx
https://github.com/mission-apprentissage/flux-retour-cfas/issues/2720
> fix: maj du lien d'aide dans le footer

- ui/pages/stats.jsx
> fix: fix mauvais lien plausible sur les stats

- .github/workflows/_deploy.yml
> feat: ajout d'une notification slack quand un déploiement commence

- ui/modules/mon-espace/SIFA/SIFAPage.jsx
> feat: ajout tracking plausible telechargement SIFA

- ui/components/Table/Table.jsx
- ui/pages/mon-espace/mes-organismes.jsx
> fix: fix de la pagination sur la page organisme

- .github/pull_request_template.md
fix #2683 
J'ai ajouté un template de pull request pour rappeler les usages, et en particulier l'obligation d'associer la PR avec une issue. Si vous voyez d'autres rappels à ajouter, n'hésitez pas.
> chore: ajout pull_request_template.md

- .infra/ansible/roles/setup/files/app/tools/cron-data-jobs/run-daily-jobs.sh
- .infra/scripts/ovh/ovh-nodejs-client/firewall.js
- server/src/common/actions/organismes/organismes.actions.ts
- server/src/common/actions/users.actions.ts
- server/src/common/model/organismes.model.ts
- server/src/common/validation/organismesFilterSchema.ts
- server/src/common/validation/paginationSchema.ts
- server/src/http/routes/admin.routes/organismes.routes.ts
- server/src/http/routes/admin.routes/stats.routes.ts
- server/src/http/routes/admin.routes/users.routes.ts
- server/src/http/server.ts
- server/src/jobs/cli.ts
- server/src/jobs/fiabilisation/stats.ts
- server/src/jobs/hydrate/organismes/hydrate-effectifs_count.ts
- ui/components/Page/components/Header.jsx
- ui/components/Table/Table.jsx
- ui/modules/admin/OrganismesList.jsx
- ui/modules/admin/UserForm.jsx
- ui/next.config.js
- ui/pages/_app.tsx
- ui/pages/admin/organismes/[id].jsx
- ui/pages/admin/organismes/index.jsx
- ui/pages/admin/users/[id].jsx
- ui/pages/admin/users/index.jsx
- ui/pages/mon-espace/mes-organismes.jsx
- ui/theme/components/text.js
> feat: ajour page gestion des organismes

- server/src/common/actions/infoSiret.actions.ts
- server/src/common/actions/organismes/organismes.actions.ts
- server/src/common/actions/uploads.actions.ts
- server/src/common/apis/ApiCfaDock.ts
- server/src/common/apis/ApiEntreprise.ts
- server/src/common/apis/apiCatalogueMna.ts
- server/src/common/apis/apiLba.ts
- server/src/common/apis/apiReferentielMna.ts
- server/src/common/apis/apiTablesCorrespondances.ts
- server/src/common/model/organismes.model.ts
- server/src/common/mongodb.ts
- server/src/common/utils/httpUtils.ts
- server/src/common/validation/objectIdSchema.ts
- server/src/common/validation/paginationSchema.ts
- server/src/common/validation/registrationSchema.ts
- server/src/common/validation/userSchema.ts
- server/src/http/routes/specific.routes/dossiers-apprenants.routes.ts
- server/src/http/routes/specific.routes/serp.routes/upload.routes.ts
- server/src/jobs/cli.ts
- server/src/jobs/db/findInvalidDocuments.ts
- server/src/jobs/db/recreateIndexes.ts
- server/src/jobs/hydrate/organismes/hydrate-effectifs_count.ts
- server/src/jobs/seed/plausible/goals.ts
- server/tests/integration/http/dossiersApprenants.route.legacy.test.ts
> chore: ajout script de recherche des docs invalides

- server/src/common/model/collections.ts
- server/src/common/model/dossiersApprenantsMigration.model.ts
- server/src/common/model/effectifs.model/effectifs.model.ts
- server/src/common/model/formations.model.ts
- server/src/common/model/indexes/index.ts
- server/src/common/model/jwtSessions.model.ts
- server/src/common/model/maintenanceMessages.model.ts
- server/src/common/model/organismes.model.ts
- server/src/common/model/organismesReferentiel.model.ts
- server/src/common/model/permissions.model.ts
- server/src/common/model/roles.model.ts
- server/src/common/model/uploads.model/uploads.model.ts
- server/src/common/model/userEvents.model.ts
- server/src/common/model/users.model.ts
- server/src/common/model/usersMigration.model.ts
- server/src/common/mongodb.ts
- server/src/common/utils/dbUtils.ts
- server/src/jobs/scriptWrapper.ts
une PR pour fixer un pb d'index. J'en ai profité pour simplifier un peu et ajouter des logs
> fix: creation des indexes

- server/src/jobs/fiabilisation/uai-siret/apply-fiabilisation/index.ts
Quick fix + ajout de log sur la partie identification des organismes non fiabilisables (mapping)
> fix(server): job fiabilisation : identification NON_FIABILISABLES_MAPPING

- server/package.json
- server/src/common/apis/ApiCfaDock.ts
- server/src/common/apis/ApiEntreprise.ts
- server/src/common/apis/apiCatalogueMna.ts
- server/src/common/apis/apiLba.ts
- server/src/common/apis/apiReferentielMna.ts
- server/src/common/apis/apiTablesCorrespondances.ts
- server/src/common/apis/client.ts
- server/yarn.lock
fix #2807
cette PR ajoute un cache adapter sur axios. https://axios-cache-interceptor.js.org/v0/
J'ai mis le TTL a 10 minutes, sachant que les ERPs ont l'air de groupé les dossiers pour un meme organisme
> feat: ajout cache axios 

- server/migrations/20230328120000-drop-useless-collections.js
un petit script de migration pour supprimer les collections liées aux modeles récemment supprimées.
> chore: suppression collections non utilisées

- server/src/jobs/cli.ts
- server/src/jobs/fiabilisation/dossiersApprenants/process-effectifs-queue-remove-duplicates.ts
fix #2807 
ce script supprime tous les doublons dans la collection effectifQueue.
> feat: ajout script pour suppression des doublons dans effectifQueue

- server/src/common/actions/effectifs.actions.ts
- server/src/common/actions/engine/engine.actions.ts
- server/src/common/actions/organismes/organismes.actions.ts
- server/src/common/actions/users.afterCreate.actions.ts
- server/src/common/model/@types/EffectifsQueue.ts
- server/src/common/model/@types/OrganismesReferentiel.ts
- server/src/common/model/effectifsQueue.model.ts
- server/src/jobs/cli.ts
- server/src/jobs/fiabilisation/dossiersApprenants/process-effectifs-queue.ts
fix #2807 
une nouvelle PR pour optimiser le process d'ingestion? En gros:
- remise a plat du process
- si un organisme avec l'UAI et le SIRET et trouvé, on n'appelle pas l'API entreprise
- redémarrage du process tous les 100 cycles (aka 10_000 dossiers traités)
> fix: optimisation du process d'ingestion

- server/src/common/actions/organismes/organismes.actions.ts
- server/src/common/model/organismes.model.ts
- server/src/jobs/hydrate/organismes/hydrate-organismes.ts
fix #2797 
cette PR ajoute 2 nouveau champs à Organisme, effectifs_current_year_count (calculé)  et qualiopi (alimenté par organismesReferentiel)
> 2797 effectifs current year count+qualiopi

- .github/workflows/_deploy.yml
une petite PR pour éviter de déployer en meme temps sur recette.
> chore: gestion des deploiements concurrents

- server/migrations/20230313180000-remove-tokenized-fields.js
- server/package.json
- server/src/common/actions/formations.actions.ts
- server/src/common/actions/organismes/organismes.actions.ts
- server/src/common/model/collections.ts
- server/src/common/model/effectifs.model/effectifs.model.ts
- server/src/common/model/effectifsQueue.model.ts
- server/src/common/model/fiabilisationUaiSiret.model.ts
- server/src/common/model/formations.model.ts
- server/src/common/model/indexes/index.ts
- server/src/common/model/jobEvents.model.ts
- server/src/common/model/json-schema/jsonSchemaTypes.ts
- server/src/common/model/jwtSessions.model.ts
- server/src/common/model/organismes.model.ts
- server/src/common/model/organismesReferentiel.model.ts
- server/src/common/model/permissions.model.ts
- server/src/common/model/roles.model.ts
- server/src/common/model/uploads.model/uploads.model.ts
- server/src/common/model/users.model.ts
- server/src/common/model/usersMigration.model.ts
- server/tests/integration/common/actions/formations.actions.test.ts
- server/tests/integration/common/actions/organismes.actions.test.ts
- server/tests/integration/db/indexes/formations.indexes.test.js
- server/yarn.lock
une petite PR pour supprimer 2 champs non utilisés
> chore: remove unused tokenized fields

- Makefile
- server/migrations/20230405120000-rename-field-organisme.formations.js
- server/src/common/actions/formations.actions.ts
- server/src/common/actions/organismes/organismes.actions.ts
- server/src/common/actions/organismes/organismes.formations.actions.ts
- server/src/common/actions/sifa.actions/sifa.actions.ts
- server/src/common/actions/uploads.actions.ts
- server/src/common/model/@types/EffectifsQueue.ts
- server/src/common/model/@types/Formation.ts
- server/src/common/model/@types/Organisme.ts
- server/src/common/model/@types/OrganismesReferentiel.ts
- server/src/common/model/organismes.model.ts
- server/src/http/routes/specific.routes/serp.routes/upload.routes.ts
- server/src/jobs/fiabilisation/uai-siret/build-fiabilisation/index.ts
- ui/common/utils/array.js
- ui/common/utils/stringUtils.js
- ui/modules/admin/UsersList.jsx
- ui/modules/mon-espace/effectifs/Televersements.jsx
- ui/modules/mon-espace/effectifs/engine/TransmissionFichier/components/UploadFiles.js
- ui/modules/mon-espace/effectifs/engine/formEngine/components/Input/Select.js
- ui/pages/admin/organismes/[id].jsx
- ui/pages/admin/users/index.jsx
fix #2808 
Cette PR fixe l'upload + apporte quelques améliorations dans le processus. 
Je suis aussi tombé sur un cas ou un organisme nous communiquait un code diplôme qu'il n'était pas censé dispenser. Du coup, j'ai modifié l'admin pour ajouter la liste des formations pour un organisme, et j'en ai profité pour renommer le champ `organismes.formations` qui était un peu troublant, parce que ce champ contient d'autres données non liées aux formations (organisme_id, uai, siret...).
> fix: fix televersement effectifs

- server/src/common/actions/organismes/organismes.actions.ts
> fix: fixe les formations et les métiers manquants sur les organismes maj

- server/src/common/utils/httpUtils.ts
> fix: cookie valide pendant 6 jours

- ui/components/legal/PolitiqueDeConfidentialite.jsx
- ui/next.config.js
> feat: suppression des mentions crisp

- .infra/ansible/ansible.cfg
- .infra/ansible/roles/deploy/tasks/main.yml
- changement du formattage de la sortie pour éviter le JSON
- ssh pipelining pour améliorer les performances
- quelques options par défaut qu'on met en général avec ansible
> feat: petites améliorations pour ansible

- server/src/http/middlewares/validateRequestMiddleware.ts
- server/src/http/routes/admin.routes/organismes.routes.ts
- server/src/http/routes/admin.routes/users.routes.ts
- server/tests/integration/common/validation/paginationSchema.test.ts
- ui/pages/admin/users/index.tsx
> fix: fix pagination sur l'admin

- ui/common/httpClient.ts
> fix: fix régression upload

- ui/modules/mon-espace/landing/visualiser-les-indicateurs/par-organisme/sections/repartition-effectifs-par-siret/RepartitionEffectifsParSiretSection.tsx
- ui/modules/mon-espace/landing/visualiser-les-indicateurs/par-organisme/sections/repartition-effectifs/IndicateursAndRepartionCfaNiveauAnneesSection.tsx
Corrige l'export des effectifs.
> fix: fix export des effectifs

- server/src/common/actions/effectifs/effectifs.actions.ts
Correction du calcul des indicateurs publics en ajoutant le filtre sur année scolaire
> fix(server): add filterStages to indicateursNational

- server/src/jobs/hydrate/reseaux/hydrate-reseaux.ts
Correction du script de chargement des réseaux pour prise en compte des établissements sans UAI via le match SIRET sur établissement FIABLE
> fix(server): chargement des réseaux pour organismes sans UAI fiables

- ui/modules/mon-espace/effectifs/engine/TransmissionFichier/components/UploadFiles.tsx
> fix: traduire msg si fichier trop volumineux

- server/src/jobs/fiabilisation/uai-siret/build.manual.ts
- server/src/jobs/fiabilisation/uai-siret/build.ts
Ajout d'une fiabilisation manuelle (vu avec Anne)
> chore(server): ajout de fiabilisation manuelles

- server/src/jobs/fiabilisation/uai-siret/update.ts
Ajout d'une règle d'update des couples de fiabilisation sur les cas ou l'on a un couple fermé & un unique couple ouvert.
> chore(server): ajout fonction de correction des couples fiables fermés

- ui/modules/auth/inscription/components/SearchBySIRETForm.tsx
- ui/modules/auth/inscription/components/SearchByUAIForm.tsx
- ui/pages/auth/inscription/profil.tsx
fix #2802
changement du message d'erreur à l'inscription si le SIRET n'est pas trouvé.
> feat: ajout du lien vers l'annuaire entreprises si siret non trouvé

- server/src/common/utils/anneeScolaireUtils.ts
- server/tests/integration/common/utils/validationUtils/anneeScolaireUtils.test.ts
> feat: changement du calcul des années scolaires pour les indicateurs

- Makefile
- docker-compose.override.yml
- server/.yarnrc.yml
- server/Dockerfile.dev
- server/package.json
- server/src/http/middlewares/logMiddleware.ts
- server/src/http/server.ts
- server/yarn.lock
cette PR fixe le déploiement en recette, corrompu depuis le merge de https://github.com/mission-apprentissage/flux-retour-cfas/pull/2937
> fix: fix esbuild multi plafforms issue with tsx

- server/tests/integration/http/organisme.routes.test.ts
> test: meilleure configuration des séquences des indicateurs

- server/src/common/actions/uploads.actions.ts
- server/src/http/routes/specific.routes/effectif.routes.ts
> fix: upload/snapshot route

- server/src/http/middlewares/logMiddleware.ts
:detective: 
Pourra permettre des analyses via grafana.
> feat: log de l'utilisateur connecté pour chaque requête

- .infra/ansible/roles/setup/files/app/tools/cron-data-jobs/run-daily-jobs.sh
- server/src/commands.ts
- server/src/jobs/clear/purge-events.ts
- server/src/jobs/clear/purge-queues.ts
> chore: script pour purger les queues de traitement

- server/migrations/20230512000000-api_v3.js
- server/migrations/20230515182100-fix-effectif-contrat.js
hotfix pour rétablir le champ effectifs.contrats
> fix: migration script pour fixer effectifs.contrats

- server/src/common/actions/engine/engine.actions.ts
- server/src/common/model/effectifsQueue.model.ts
- server/src/jobs/fiabilisation/dossiersApprenants/process-effectifs-queue.ts
- server/tests/integration/jobs/process-effectifs-queue.test.ts
un hot fix pour un cas mal géré, i.e quand une exception est levée dans le transform de schema Zod.
Coté donnée, rien n'est perdu, c juste que le process a 13h de retard de traitmement.
> fix(server): catch les exceptions dans le transform du schema d'ingestion

- server/src/http/server.ts
petite PR pour fixer le lien "mot de passe oublié"
> fix(server): fix validation zod sur /forgotten-password

- server/src/commands.ts
- server/src/jobs/fiabilisation/dossiersApprenants/remove-nonRecus-depuis/index.js
Correction du script, prise en compte des inscrits sans contrats dans ce statut depuis X jours (vu coté métier)
> fix(server): script de suppression des inscrits sans contrats dans ce statut depuis X jours

- server/src/commands.ts
- server/src/jobs/fiabilisation/dossiersApprenants/remove-nonRecus-depuis/index.js
Script de transformation des rupturants dans ce statut depuis 180jours en abandon (validé coté métier)
> chore(server): transformation rupturants en abandons 180 jrs

- ui/modules/dashboard/NewDashboardTransverse.tsx
> fix(ui): tooltip d'explication sur la carte du taux de couverture des organismes

- ui/modules/dashboard/SimpleOverlayMenu.tsx
- ui/modules/indicateurs/filters/FiltreFormationCFD.tsx
- ui/modules/indicateurs/filters/FiltreOrganismeTerritoire.tsx
> fix(ui): largeur maximale à chakra-size-xl sur les modales

- server/package.json
- server/src/commands.ts
- server/src/jobs/seed/start/index.ts
J'ai repris ce que j'ai eu à lancer. Il manque les effectifs, mais je ne sais pas si je peux partir de ce que j'ai eu (sont-ce des données utilisables)
> chore: nouvelle commande init:dev pour lancer les commandes hydrate de démarrage

- ui/modules/mon-espace/effectifs/EffectifsBannerERPNotConfigured.tsx
Corrige le centrage dans la page mes effectifs.
Les bug remontés par Nadine sur la page dashboard d'un OF a dû être corrigé avec les dernières PR et le nettoyage.
> fix: corrige un problème de layout sur mes effectifs

- ui/modules/dashboard/DashboardTransverse.tsx
- ui/modules/dashboard/IndicateursGrid.tsx
- ui/pages/index.tsx
Voir les commits. Des correctifs mineures + styles
> fix: corrections mineures

- ui/modules/indicateurs/IndicateursForm.tsx
> fix: correction label réseau d'organismes

- server/src/common/actions/indicateurs/indicateurs.actions.ts
- server/tests/integration/http/indicateurs.route.test.ts
- Changement format : AAAA-MM-DDT00:00:00.000Z --> AAAA-MM-DD
- test minimal de la route d'export des données
> fix: revue du format d'export des dates

- server/src/common/services/mailer/emails/common/signature.ejs
- ui/pages/index.tsx
La mission n'a plus le même nom, validé avec Catherine.
> chore(ui): remove "et les trajectoires professionnelles

- ui/pages/index.tsx
- Correction de typos remontées par Catherine,
- Potentiellement une autre correction à faire dans le bloc Nos missions + Simplifie**z**, mais actuellement rejeté par Nadine.
> fix(ui): wording infinitif => impératif

- server/src/common/apis/apiLba.ts
- server/tests/integration/common/actions/formations.actions.test.ts
- server/tests/utils/nockApis/index.ts
- server/tests/utils/nockApis/nock-Lba.ts
Suite à message d'Alan sur slack, ajout du préfixe v1 dans la route appelée. (mise à jour des métiers, non encore utilisé à ma connaissance.)
> fix: maj du chemin route lba

- ui/components/tooltips/TooltipNatureOrganisme.tsx
- ui/modules/indicateurs/IndicateursForm.tsx
- ui/modules/indicateurs/filters/FiltreFormationCFD.tsx
- ui/pages/organismes.tsx
Basé sur une discussion avec Catherine et https://www.figma.com/file/0mofiw6xvEKFnvdIjl5Whl/DSFR-x-TdB?type=design&node-id=460-71749&t=K1Y7ma8UEDexauQn-0
> feat(ui): nouveaux tooltips

- .vscode/settings.json
- server/src/commands.ts
- server/src/common/model/@types/OrganismeSoltea.ts
- server/src/common/model/collections.ts
- server/src/common/model/organismesSoltea.model.ts
- server/src/jobs/hydrate/organismes/hydrate-organismes-soltea.ts
Petite PR pour ajouter une collection organismes SOLTEA issue d'un fichier externe fourni. 
Sera utilisée pour faire des croisements entre nos organismes non fiables et cette collection dans un premier temps (cc @felixat13)
> chore(server): ajout d'une collection organismes SOLTEA pour analyse / fiabilisation

- server/src/jobs/fiabilisation/uai-siret/update.ts
Anomalie sur la condition de fiabilisation.
Qqs organismes concernés
> fix(server): organismes fiables ouverts seulement

- server/src/common/actions/organismes/organismes.actions.ts
- server/src/common/constants/territoires.ts
- server/src/common/model/json-schema/adresseSchema.ts
- ui/common/constants/territoires.ts
2 petits correctifs qui provoquent un delta entre les organismes du référentiel et les organismes du tdb avec est_dans_le_referentiel = true.
> fix(server): correctifs sur l'hydrate organismes

- .infra/ansible/roles/setup/files/app/.overrides/common/docker-compose.common.yml
[Urgent]: https://www.metabase.com/blog/security-advisory
> fix: upgrade metabase version to v0.46.6.1

- ui/modules/organismes/ListeOrganismesPage.tsx
[TM-178](https://tableaudebord-apprentissage.atlassian.net/browse/TM-178)
> feat: ajout nombre d'établissements non fiables fermés

- server/src/common/actions/helpers/permissions.ts
- server/src/common/actions/indicateurs/indicateurs.actions.ts
- server/tests/integration/http/indicateurs.route.test.ts
- ui/modules/indicateurs/IndicateursForm.tsx
Corrige [TM-177](https://tableaudebord-apprentissage.atlassian.net/browse/TM-177)
> fix: un opérateur publique national ne peut plus télécharger les listes nominatives

- server/package.json
Make server debugging great again!
@sbenfares :grin:
> chore: exposition du port debug du serveur

- server/src/common/actions/organismes/organismes.actions.ts
- server/src/jobs/fiabilisation/uai-siret/build.ts
- server/src/jobs/ingestion/process-ingestion.ts
This reverts commit 394b51360e799d10bfdf2ad41a9a56d18f0ca16d.
> Revert "fix(server): correction de l'ingestion et des scripts de fiabilisation (#3112)"

- ui/components/Page/components/NavigationMenu.tsx
- ui/pages/glossaire.tsx
Le figma est ici : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?node-id=12344%3A277605&mode=dev
Discuté hier avec Catherine qui perçoit une valeur forte lors des entretiens, c'est dans le sprint 5 (noté par Barbara). Ça m'a pris une heure (ça détend, c'est facile), on continue dans la démarche de valider nous même
> feat(ui): ajout de la page glossaire

- server/src/common/actions/organismes/organismes.actions.ts
(en attente que les tests passent mais c'est bon sur mon poste pour ceux que j'ai testé)
> chore: re-add info on organismes

- server/src/common/actions/organismes/organismes.actions.ts
- server/src/common/actions/organismes/organismes.formations.actions.ts
- server/src/http/routes/admin.routes/organismes.routes.ts
Suppressions de quelques fonctions qui n'étaient pas utilisées dans organisme
> chore(server): remove organismes useless actions

- server/src/common/actions/legacy/users.legacy.actions.ts
- server/src/jobs/users/create-user.ts
- server/tests/integration/common/actions/users.legacy.actions.test.ts
SUppression des fonctions dite "legacy" users (je ne connais pas trop l'histoire derrière) qui ne sont utilisées nulle part à part dans leurs propres tests :)
> chore(server): remove users legacy unused functions

- server/src/common/actions/effectifs/effectifs.actions.ts
- server/src/common/actions/effectifs/indicator.ts
- server/src/common/actions/engine/engine.actions.ts
- server/src/common/actions/engine/engine.organismes.utils.ts
- server/tests/integration/common/actions/organismes.actions.test.ts
Supression de code mort uniquement, sans prise de risque trop élevée. Le seul risque que je vois serait que des fonctions soient appelées avec des noms dynamiques construits à partir de chaine.
> chore(server): clean dead code backend

- server/src/common/actions/emails.actions.ts
- server/src/common/utils/asyncUtils.ts
- server/src/common/utils/cryptoUtils.ts
- server/src/http/routes/specific.routes/upload.routes.ts
- server/tests/integration/common/actions/organismes.actions.test.ts
- server/tests/integration/common/actions/users.legacy.actions.test.ts
- server/tests/integration/db/indexes/formations.indexes.test.ts
- server/tests/integration/db/indexes/users.indexes.test.ts
- server/tests/utils/nockApis/nock-tablesCorrespondances.ts
- ui/modules/indicateurs/IndicateursForm.tsx
- ui/modules/mon-espace/effectifs/engine/Effectif.tsx
- ui/modules/mon-espace/effectifs/engine/Effectifs.tsx
- ui/modules/mon-espace/effectifs/engine/EffectifsTable.tsx
~A merger après les nouveaux profils carif oref. #3133~
3 améliorations mineures, voir les 3 commits.
> fix: contexte messages bandeau indicateurs + autres améliorations

- ui/modules/indicateurs/filters/FiltreFormationNiveau.tsx
cf https://www.notion.so/mission-apprentissage/Filtre-Niveau-de-formation-d85dd088a42f41c395b2f851ebc980f0
Même si aucun effectif en doctorat en prod... :shrug:
> feat: ajout du niveau de formation doctorat

- server/src/jobs/hydrate/reseaux/hydrate-reseaux.ts
Correction d'hydrate réseaux - query de recherche des organismes par siret étant présent dans le référentiel.
> fix(server): query find organisme by siret in referentiel

- ui/components/SelectButton/SecondarySelectButton.tsx
Corrige (a priori) :point_down:
> fix: supprime un warning lié au date picker

- ui/pages/glossaire.tsx
- ui/styles/globals.css
- ui/theme/components/table.js
Cf: https://www.notion.so/mission-apprentissage/Glossaire-e572de00f6ef41ee85cee0f014a6f24f
> fix: amélioration du glossaire

- server/src/jobs/ingestion/process-ingestion.ts
Correction de l'ingestion pour y ajouter la récupération des niveaux des formations depuis le catalogue.
En plus de corriger lors de l'ingestion il faudra une fois déployé, lancer manuellement un script qui corrige les effectifs déja présents en base 
👉🏼  `yarn cli hydrate:effectifs-formation-niveaux`
> fix(server): ajout du niveau depuis le catalogue lors de l'ingestion

- .bin/scripts/build-images.sh
- .github/workflows/_deploy.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/preview.yml
- .github/workflows/preview_cleanup.yml
- .github/workflows/release.yml
https://github.com/actions/checkout/issues/1448
> fix: image version

- ui/modules/organismes/Televersement.tsx
Parce que sinon ça dit : 
todo: rebase sur master quand l'infra est finie !
> fix: on extrait les lignes complètement vides du téléversement

- server/src/common/model/effectifs.model/parts/contrat.part.ts
Voir: https://mission-apprentissage.slack.com/archives/C02FR2L1VB8/p1693925179064389?thread_ts=1693908625.524139&cid=C02FR2L1VB8
J'imagine qu'il faut être attentif à la CI. Si ça passe pas je peux reprendre un autre jour
> fix: suppression de la date de fin obligatoire sur les contrats

- ui/modules/dashboard/DashboardOrganisme.tsx
cf: https://mission-apprentissage.slack.com/archives/C02G31Y8WKH/p1693926944173809
> fix: affichage de l'année scolaire dans les indicateurs d'un organisme

- .talismanrc
- ui/modules/organismes/Televersement.tsx
> fix: lien mailto dans le téléversement

- ui/modules/indicateurs/IndicateursForm.tsx
https://tableaudebord-apprentissage.atlassian.net/browse/TM-264
> fix: ne pas afficher le ruban quand il n'y a pas de texte (tm-264)

- server/src/common/model/effectifs.model/parts/formation.effectif.part.ts
- server/src/common/validation/dossierApprenantSchemaV3.ts
- server/tests/integration/jobs/ingestion/process-ingestion.test.ts
~~En attente des retours des tests~~
> fix: le cfd n'est plus obligatoire en v3

- server/src/common/actions/organismes/organismes.actions.ts
Correction nécessaire pour les analyses de @felixat13 !
> fix: calcul de l'année scolaire pour les compteurs d'effectifs

- ui/modules/dashboard/DashboardOrganisme.tsx
Redirige vers le dictionnaire des données de l'API v3.
> feat: ajout lien données collectées quand dashboard organisme vide

- server/src/jobs/ingestion/process-ingestion.ts
Source: https://mission-apprentissage.slack.com/archives/C02FR2L1VB8/p1695295051135549
> feat: calcul de la durée réelle de la formation si possible

- server/src/commands.ts
- server/src/http/server.ts
cf titre + déplacement dans une commande au cas où.
> chore: suppression du listing des routes au démarrage

- server/src/common/model/effectifs.model/parts/formation.effectif.part.ts
- ui/modules/mon-espace/effectifs/engine/cerfaForm/blocks/apprenant/EffectifApprenant.tsx
- ui/modules/mon-espace/effectifs/engine/cerfaForm/blocks/apprenant/apprenantSchema.ts
- ui/modules/mon-espace/effectifs/engine/cerfaForm/blocks/formation/EffectifFormation.tsx
- ui/modules/mon-espace/effectifs/engine/cerfaForm/blocks/formation/formationSchema.ts
https://tableaudebord-apprentissage.atlassian.net/browse/TM-318
> fix: ajout de nouveaux champs dans les informations d'un effectif

- server/src/common/constants/models/upload.models.part.ts
- server/src/common/constants/upload.ts
- server/src/common/model/effectifs.model/parts/apprenant.part.ts
- server/src/http/routes/specific.routes/upload.routes.ts
Ce champ est indiqué comme obsolète depuis longtemps. Son remplaçant était rqth
> chore: suppression de la valeur handicap (obsolete)

- server/src/http/routes/specific.routes/dossiers-apprenants.routes.ts
Cf: https://mission-apprentissage.slack.com/archives/C02G31Y8WKH/p1695641538704459
> fix: augmentation de la limite d'envoi de dossier apprenants

- .infra/files/configs/reverse_proxy/locations/70_smtp.conf.template
- .infra/files/configs/reverse_proxy/locations/80_metabase.conf.template
Pour @rap2hpoutre 
Je n'ai pas eu la possibilité de tester évidemment, comme on a pas le même environnement en local qu'en prod, mais j'ai bon espoir...
> chore: urls /smtp/ + /metabase/ avec slash facultatif

- server/src/common/services/sentry/sentry.ts
cf: https://mission-apprentissage.slack.com/archives/C02G31Y8WKH/p1695730466169029?thread_ts=1695720669.666449&cid=C02G31Y8WKH
> fix: desactivation de sentry le temps qu'il soit configuré

- server/src/db/migrations/20230926125212-clean-organismes-erps.ts
- server/src/db/migrations/20230926133135-deduplicate-organismes-erps.ts
Migrations de nettoyage suite à qqs cas impropres (vu avec @felixat13)
> feat(server): nettoyage du champ ERPs des organismes

- ui/modules/organismes/Televersement.tsx
> fix: on signale les colonnes qui manquent dans le téléversement

- ui/hooks/organismes.ts
- ui/modules/organismes/models/organismes-filters.ts
Corrige les organismes qui étaient rechargés à chaque maj des filtres.
> fix: reload organismes

- server/src/common/actions/sifa.actions/sifa.actions.ts
J'avais oublié ça : https://mission-apprentissage.slack.com/archives/C02FR2L1VB8/p1695308447288739
> fix(sifa): on ajoute les UAI d'organismes quand disponibles

- ui/modules/indicateurs/permissions-onglet-graphique.ts
- ui/pages/indicateurs/graphiques.tsx
onglet dataviz pour les têtes de réseau !
> feat: onglet dataviz pour les têtes de réseau

- server/src/common/actions/engine/engine.actions.ts
cf: https://mission-apprentissage.slack.com/archives/CUV45LDNY/p1696599654866419
> fix: les adresses peuvent planter quand la région n'est pas trouvée (api v2 v3)

- server/src/db/migrations/20231012000001-clean-up-old-organismes-configuration.ts
> feat: nettoyage setup_step_courante

- ui/modules/effectifs/EffectifsPage.tsx
Corrige une [régression](https://github.com/mission-apprentissage/flux-retour-cfas/pull/3270/commits/78195cb8ce2cba008e497704d992e6107cc375a9#r1358217685)  suite au refacto effectifs / paramètres.
> fix: filtre annee scolaire explicite vs variables locales

- ui/modules/organismes/Televersement.tsx
https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?type=design&node-id=14202-33056&mode=design&t=hhd2JNtQnnKN6OQC-0
> fix: plus d'infos sur les champs obligatoire du téléversement

- server/src/common/validation/utils/zodPrimitives.ts
- server/tests/integration/http/indicateurs-national.route.test.ts
C'est une régression, du coup d'ancien fichiers excel qui passaient ne passent plus
> fix: le numéro de téléphone peut-être numérique à nouveau (ce qui arrive dans les imports excel)

- server/src/common/actions/indicateurs/indicateurs-national.actions.ts
- server/tests/integration/http/indicateurs-national.route.test.ts
- ui/pages/index.tsx
C'est là : https://mission-apprentissage.slack.com/archives/C02FR2L1VB8/p1697202878750679?thread_ts=1697202664.902759&cid=C02FR2L1VB8
> fix: ofa avec date de transmission comme sur la maquette figma (todo: fix me)

- .infra/docker-compose.production.yml
Corrige peut-être https://mission-apprentissage.slack.com/archives/C02G31Y8WKH/p1697636736858579
:shrug:
> fix: update metabase to 0.47.4

- server/src/jobs/jobs.ts
Fix le cron des emails de relance qui ne s'exécutait pas.
> fix: reminder emails job name

- ui/modules/dashboard/IndicateursGrid.tsx
- ui/modules/indicateurs/IndicateursForm.tsx
- ui/modules/organismes/OrganismesTable.tsx
> feat: ajout title quand boutons téléchargements désactivés

- server/src/common/actions/organismes/organismes.actions.ts
- ui/modules/indicateurs/IndicateursForm.tsx
- ui/modules/indicateurs/NewTable.tsx
- ui/modules/organismes/ListeOrganismesPage.tsx
- ui/pages/organismes.tsx
- ui/pages/organismes/[organismeId]/organismes.tsx
- ui/pages/organismes/[organismeId]/organismes/a-completer.tsx
- ui/pages/organismes/a-completer.tsx
> feat: ajouter l'organisme courant dans les organismes

- ui/modules/organismes/Televersement.tsx
Source : https://www.notion.so/mission-apprentissage/Tests-t-l-versement-V2-am-liorations-du-front-cf94f348b36440358ed0211c9efcb5c8
> - **Page d’analyse du fichier** : Mettre un interrupteur pour n’afficher que les colonnes qui comportent des erreurs
>    Cela permettra une meilleure lisibilité et lecture rapide des données à corriger par les users
Coût tech estimé par Raphaël : 2h
> fix: on peut n'afficher que les colonnes en erreurs sur le téléversement

- server/src/common/actions/organisations.actions.ts
- server/src/common/services/mailer/mailer.ts
- server/static/emails/notify_access_granted_ofa.mjml.ejs
> feat: amélioration email de bienvenue pour les OFA

- server/src/jobs/fiabilisation/effectifs/index.ts
- server/src/jobs/fiabilisation/uai-siret/build.ts
Remplacement des années scolaires en dur par l'appel à la fonction getAnneesScolaireListFromDate
> feat(server): remplacement des années scolaires en dur par la fonction getAnneesScolaireListFromDate

- .infra/ansible/deploy.yml
- .infra/files/configs/reverse_proxy/owasp-crs/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
Move rules exceptions per projects
> chore: fix waf settings

- server/src/db/migrations/20231025102145-remove-source-value-objectId-in-effectifs.ts
MAJ des sources de effectifs ayant un objectId comme étant issu du téléversement.
A valider par @rap2hpoutre ?
> feat(server): update des effectifs ayant pour source un objectId en source = televersement

- ui/modules/organismes/Televersement.tsx
L'idée c'est d'avoir une vue encore plus compacte : on peut masquer les lignes en succès (et on réinitialise à chaque upload)
> fix: afficher uniquement les colonnes et lignes en erreur dans l'import excel

- ui/pages/index.tsx
https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/TM/boards/1/backlog?selectedIssue=TM-411
https://www.notion.so/mission-apprentissage/e14221ce159c440c9d4fbd5149f7d035?v=e9db7aad1ded416e850e797a639c81e4&p=a5fa96bc7ea94ba7bbbe49e53cec5b6a&pm=s
> feat: afficher le taux de couverture en pourcent

- ui/modules/organismes/InfoTeleversement.tsx
- ui/modules/organismes/Televersement.tsx
> feat: texte de conseils et recommandations du televersement

- ui/modules/organismes/IndicateursEffectifsParFormationTable.tsx
Petit fix sur le dashboard d'un organisme.
> fix: désactivation du lien RNCP quand pas de fiche trouvée

- ui/modules/organismes/headerTooltips.tsx
Vu en direct parce que certains organismes se plantent (sur ça aussi)
> fix: plus d'info sur le tooltip ine

- server/src/jobs/hydrate/open-api/schema.ts
- server/static/open-api.json
pour faire plaisir à gestibase
> chore: passage de la doc de processed_at en optionnel

- ui/components/Page/components/NavigationMenu.tsx
- ui/pages/index.tsx
Permet de passer de ça :
---
---
à :
---
---
Et potentiellement :
> style: amélioration de la page d'accueil sur mobile

- ui/modules/organismes/Televersement.tsx
> fix: remplacer refonte par amélioration sur le téléversement

- server/src/common/validation/utils/zodPrimitives.ts
Préparez vous à une série de PR euh... pas très dures à vérifier (typos et autres)
> fix: message d'erreur de la durée théorique de formation en français

- ui/common/exports.ts
- ui/pages/admin/users/index.tsx
Contexte : 
> Si tu as 5 minutes, j’ai une PR un peu urgente au vu du flux dutilisateurs qui arrivent.
Comme ils galèrent à s’y retrouver, en attendant de faire un système de filtre bien fait qui nous prendrait plusieurs heures, j’ai fait un système d’export excel de tout en quasi brut
> feat: téléchargement de la liste des utilisateurs (quasi-brute)

- ui/modules/organismes/headerTooltips.tsx
> fix: amélioration tooltips de téléversement année scolaire, dernière situation et  siret employeur

- ui/modules/dashboard/DashboardOrganisme.tsx
Ajout de tooltip lorsque l'UAI ou la nature sont inconnue.
Cf maquette : https://www.figma.com/file/gvkK8ctXygZxGrjL23s5x4/TBA?type=design&node-id=14620%3A52856&mode=design&t=Y3pkU0KMzpLdZESk-1
> feat(ui): ajout tooltips uai inconnue & nature inconnue

- server/src/common/model/effectifs.model/parts/apprenant.part.ts
- server/src/common/validation/utils/zodPrimitives.ts
- server/src/http/routes/specific.routes/organisme.routes.ts
- server/src/http/server.ts
- ui/modules/mon-espace/effectifs/engine/effectifForm/EffectifForm.tsx
- ui/modules/mon-espace/effectifs/engine/effectifForm/blocks/apprenant/EffectifApprenant.tsx
- ui/modules/mon-espace/effectifs/engine/effectifForm/blocks/apprenant/apprenantSchema.ts
- ui/modules/mon-espace/effectifs/engine/formEngine/components/Input/Input.tsx
- ui/modules/mon-espace/effectifs/engine/formEngine/components/Input/InputController.tsx
https://mission-apprentissage.slack.com/archives/C02FR2L1VB8/p1700238378161479
> feat: ajout de l'option appliquer à tous

- ui/modules/dashboard/CarteFrance.tsx
- ui/modules/models/graphs.ts
> fix: la borne supérieure n'était pas prise en compte dans l'affichage de la carte de France

- ui/package.json
- yarn.lock
Petit souci avec l'ancienne version de la lib ou dans certains cas le fichier en sortie était corrumpu ou erroné si beaucoup d'OFA dans la liste.
L'upgrade vers la dernière version semble corriger le souci 🤞🏼
> feat(ui): upgrade xlsx

- server/src/common/validation/utils/zodPrimitives.ts
- server/tests/integration/jobs/ingestion/process-ingestion.test.ts
Le problème est que gestibase envoie des chaines vides pour les téléphones, du coup on peut considérer ça comme null, ce qui enlèvera 90% des erreurs de gestibase 🎉
> feat: on accepte les numéros de téléphone en chaine vide (cf gesti) + ajouts de tests

- ui/components/legal/Accessibilite.tsx
- ui/pages/accessibilite.tsx
cf: https://tableaudebord-apprentissage.atlassian.net/browse/TM-494
> fix: nouvelle déclaration d'accessibilité

- ui/components/Page/components/Footer.tsx
Cf: https://mattermost.incubateur.net/betagouv/pl/m1rdk6gwaiyqjdnoehemjexsua
> fix: il est possible que dashloard ne détecte pas non conforme avec une majuscule

- ui/modules/mon-espace/effectifs/engine/formEngine/components/Input/InputController.tsx
https://tableaudebord-apprentissage.atlassian.net/browse/TM-463?atlOrigin=eyJpIjoiOGU5MzM0ZmE0NmUyNDU2ODgzYzgxMzc1NTNiN2NkMmMiLCJwIjoiaiJ9
> feat: on autorise la modification d'un champ verrouillé quand celui-ci est vide

- server/src/http/server.ts
- ui/pages/mentions-legales.tsx
Fix: https://mission-apprentissage.slack.com/archives/C02G31Y8WKH/p1701081068198759?thread_ts=1701078925.759499&cid=C02G31Y8WKH
> fix: ssr pour les mentions légales

- .talismanrc
- server/src/common/actions/effectifs.actions.ts
- server/src/db/migrations/20231128140152-remove_is_lock_on_empty_properties.ts
- server/tests/integration/common/actions/helpers/flatPathsWithoutEmpty.test.ts
~~Je n'arrive pas à lancer la migration chez moi, donc je garde tant que j'aurai pas réussi :/~~
@sbenfares Chez moi la migration va vite, mais j'ai une petite base de données. Si tu as moyen de tester sur une base de données plus grosse ça me rassurerait :)
> fix: on ne lock plus les champs empty (+rétrocorrection)

- server/tests/integration/common/actions/organismes.actions.test.ts
- server/tests/utils/nockApis/nock-apiEntreprise.ts
Correction des tests sur appels API Entreprise via correction du nockApi
> feat(server): update tests call API Entreprise & nock

- server/src/jobs/ingestion/process-ingestion.ts
> fix: ne pas verrouiller les champs quand import excel

- ui/modules/organismes/ListeOrganismesPage.tsx
Vu en direct avec Nadine et Catherine
> fix: précisions et liens dans le bandeau des organismes

- ui/modules/organismes/InfoTeleversement.tsx
https://tableaudebord-apprentissage.atlassian.net/browse/TM-474
> fix: amélioration du texte et lien vers un convertisseur pour le téléversement

- server/src/common/actions/indicateurs/indicateurs-national.actions.ts
- ui/pages/index.tsx
cf: https://mission-apprentissage.slack.com/archives/C02FR2L1VB8/p1702369011216759
> fix: les indicateurs nationaux donnent tous les organismes transmetteurs indépendamment de la date

- server/src/db/migrations/20231212094007-double_erps.ts
https://tableaudebord-apprentissage.atlassian.net/browse/TM-561
> fix: suppression des noms d'erp en double dans la bandeau de transmission

- server/src/db/migrations/20231211152119-mode_de_transmission.ts
@sbenfares Comme d'habitude ma base de données n'est pas terrible, si tu peux tester sur la tienne c'est probablement mieux !
> fix: mise à jour des organismes pour réparer l'encart admin et le paramétrage quand il est déjà fait

- server/src/common/actions/helpers/permissions-organisation.ts
- server/src/common/actions/helpers/permissions-organisme.ts
Première partie du ticket https://tableaudebord-apprentissage.atlassian.net/browse/TM-438
> feat: tete de réseau compagnon du devoir peut télécharger la liste nominative des effectifs

- server/src/common/validation/utils/frenchTelephoneNumber.ts
- server/tests/integration/common/utils/validationUtils.test.ts
cf: https://cfas.apprentissage.beta.gouv.fr/metabase/question/1080-toutes-les-ingestions-de-lof-selectionne-2023-2024?uai=0134480Z
> fix: on accepte (et corrige) les numéros de tel qui commencent par un plus entre parenthèses

- server/src/common/model/effectifs.model/parts/apprenant.part.ts
- server/src/common/validation/utils/zodPrimitives.ts
Baisse du contrôle de coherence de l’INE
[TM-576](https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/TM/boards/1/backlog?assignee=712020%3Aa35d39f1-286a-43a4-8ad3-c1041b95d2a1&selectedIssue=TM-576)
> fix: baisse du controle de coherence de l’ine

- server/src/jobs/ingestion/process-ingestion.ts
J'ai remonté trois mois de commit et ça semble toujours avoir été là ....
> fix: on n'efface plus la date de création à chaque mise à jour

- .talismanrc
- server/src/jobs/hydrate/reseaux/hydrate-reseaux.ts
- server/src/jobs/ingestion/process-ingestion.ts
- server/src/jobs/patches/update-lastTransmissionDates/index.ts
- server/src/jobs/users/generate-password-update-token.ts
- server/tests/integration/common/actions/effectifs.duplicates.actions.test.ts
- ui/modules/admin/InfoDetail.tsx
Suite de : https://github.com/mission-apprentissage/flux-retour-cfas/pull/3457
> chore: amélioration du code depuis jsdoc vers typescript step 2

- ui/modules/dashboard/DashboardTransverse.tsx
- ui/modules/dashboard/hooks/usePublicIndicateursCoverage.tsx
- ui/modules/dashboard/hooks/usePublicIndicateursEffectifs.tsx
- ui/modules/models/effectifs-filters.ts
Travaux préliminaire à https://tableaudebord-apprentissage.atlassian.net/browse/TM-567 pour la création de la page d'accueil similaire au dashboard
> fix: création de hooks pour les indicateurs public
