docker-compose.override.yml

Simplification du docker-compose.override au niveau des variables d'env & utilisation du .env
Dépends de https://github.com/mission-apprentissage/flux-retour-cfas/pull/2213

chore: clean docker-compose.override remove env var & use .env

---

server/src/common/actions/maintenances.actions.js
server/src/common/model/next.toKeep.models/maintenanceMessages.model.js
server/src/http/middlewares/authMiddleware.js
server/src/http/middlewares/pageAccessMiddleware.js
server/src/http/routes/admin.routes/maintenances.routes.js
server/src/http/server.js
server/tests/integration/http/maintenances.route.test.js
server/tests/utils/testUtils.js
ui/pages/admin/maintenance.jsx

Cette PR ajoute un page de maintenance dans la console d'admin pour pouvoir créer / mettre a jour des messages de maintenance. 
Video: https://youtu.be/65yyOI4q-8E
A venir: une autre PR pour afficher les messages sur le site.
[EDIT] petit erreur de push, le commit a été envoyé dans refacto [ici](https://github.com/mission-apprentissage/flux-retour-cfas/commit/7a6e3d48ed96c89ec3dc3cfab9e68cdd5502bedf), et cette PR ne contient plus que les tests. Sorry!

feat: ajout page /admin/maintenance

---

.github/workflows/cron-recette.yml
server/.eslintrc
server/tests/data/randomizedSample.js
server/tests/recette/jobs/send-dossiers-apprenants/index.js
server/tests/utils/api.js

Cette PR ajoute un job de test pour la plateforme recette, pour importer toutes les nuits un jeu de dossiers apprenants de test en recette.
Le job est executé toutes les nuits à 04h00 à l'aide de github actions. C'est une proposition de workflow, si pas possible, on peut bien sur en discuter pour trouver une alternative. 
J'ai ajouté un helper server/tests/utils/api.js pour appeler l'api, avec l'idée qu'on pourrait réutiliser ce helper dans les tests d'integration dans le futur.
**TODO**
ajouter 2 gh secrets pour se connecter à la recette:
- API_RECETTE_USERNAME
- API_RECETTE_PASSWORD

feat: ajout d'un cron job pour import dossiers apprenants sur platforme recette

---

.github/workflows/cron-recette.yml

Un fix rapide pour mettre a jour le nom de la branche qui est utilisé pour le cron de creation du jeu de test en recette.

fix: branch dans le wortkflow cron-recette.yml

---

reverse_proxy/app/nginx/templates/modsecurity.d/modsecurity-override.conf.template

Jusqu'a recemment le script `node server/tests/recette/jobs/send-dossiers-apprenants/index.js` permettait d'envoyer 100 records au server de recette, mais depuis peu nginx bloque la requete (sur recette, et reproduit en local) et renvoie l'erreur "Failed to fully parse request body due to large argument count".
Cette erreur est en fait renvoyée par la regle mod-security 200007 (cf [ici](https://github.com/SpiderLabs/ModSecurity/blob/5dfc0a256a27ea6245a972a2a6ab9c1a4edd2599/modsecurity.conf-recommended#L68)), qui bloque la requete quand celle ci contient un message json contenant plus de 1000 champs a parser.
➡️  Cette PR supprime la regle 200007 et en crée une nouvelle pour permettre l'envoi de jusqu'à 2000 champs.
J'imagine que des nouveaux champs ont été introduit avec le refactoring, …

fix: fix nginx error "Failed to fully parse request body due to large argument count"

---

server/src/common/actions/engine/engine.actions.js

Il y'avait une erreur dans le hydrateEffectifs qui fait que les effectifs sont vides en recette. 
Dans le dateConverter, on passait des dates au format string et d'autre en date.

fix(server): dateConverter toIsoString in hydrateEffectifs

---

server/src/common/actions/engine/engine.actions.js
server/src/common/actions/organismes/organismes.actions.js
server/src/common/actions/organismes/organismes.formations.actions.js
server/src/common/actions/sifa.actions/sifa.actions.js
server/src/common/actions/users.afterCreate.actions.js
server/src/http/middlewares/permissionsOrganismeMiddleware.js
server/src/http/middlewares/requireJwtAuthentication.js
server/src/http/routes/specific.routes/espace.routes.js
server/src/http/routes/specific.routes/old/dossiers-apprenants.route.js
server/src/http/routes/specific.routes/organisme.routes.js
server/src/jobs/hydrate/_toRemove/organismes/hydrate-organismes-formations.js
server/src/jobs/hydrate/_toRemove/organismes/hydrate-organismes-referentiel.js
server/src/jobs/hydrate/_toRemove/reseaux/hydrate-reseaux.js
server/src/jobs/hydrate/organismes/hydrate-organismes-and-formations.js
server/src/jobs/hydrate/reseaux/hydrate-reseaux-new-format.js
server/src/jobs/patches/refacto-migration/dossiersApprenants/dossiersApprenants.migration.js
server/src/jobs/patches/refacto-migration/organismes/organismes.migration.job.actions.js
server/src/jobs/patches/refacto-migration/organismes/organismes.migration.js
server/src/jobs/seed/samples/seedSample.js
server/src/jobs/seed/start/index.js
server/tests/integration/common/actions/organismes.actions.test.js
server/tests/integration/db/indexes/organismes.indexes.test.js
server/tests/integration/http/dossiersApprenants.route.legacy.test.js
server/tests/integration/http/effectifs.route.test.js

- Création d'un dossier organismes dans actions, avec ajout d'un organismes.formations.actions.js
- Construction de l'arbre des formations liés à un organisme au moment de la création de l'organisme.
- Temporairement le code est en doublon dans le job d'hydrate et la méthode createOrganisme uniquement pour pouvoir logger en détail dans le job si besoin d'analyse.
- Fix de doublons identifiés sur le formation_id
- Update du seed:sample pour éviter de throw si un user existe déja

chore(server): build organisme formations tree on createOrganisme

---

.infra/ansible/roles/setup/files/app/tools/cron-data-jobs/run-analyse-fiabilite-donnees-recues-job.sh
.infra/ansible/roles/setup/files/app/tools/cron-data-jobs/run-daily-jobs.sh

Désactivation (temporaire) des jobs CRON
Le temps qu'on lance les scripts de migration pour éviter les conflits je propose de désactiver (commentés) ces lancements de jobs. Voir ensemble ce qu'on gardera après.

chore(infra): desactivate cron jobs (temporary)

---

server/src/common/components/components.js
server/src/common/components/effectifs-dossiers-old/abandons.dossiers.js
server/src/common/components/effectifs-dossiers-old/apprentis.dossiers.js
server/src/common/components/effectifs-dossiers-old/indicator.dossiers.js
server/src/common/components/effectifs-dossiers-old/inscrits-sans-contrats.dossiers.js
server/src/common/components/effectifs-dossiers-old/rupturants.dossiers.js
server/src/common/components/effectifs.dossiers.old.js
server/src/http/routes/specific.routes/old/indicateurs-national.dossiers.old.route.js
server/src/http/routes/specific.routes/old/indicateurs.dossiers.old.route.js
server/src/http/server.js

Petite PR d'ajout de routes temporaires pour voir les indicateurs en se basant sur l'ancien modèle DossiersApprenants.
Un peu dirty car copier / coller de composant mais c'est du temporaire pour la recette / comparaison des données.
Utilisable en appelant : `/api/indicateurs-national-dossiers-old` et `/api/indicateurs-dossiers-old`

chore(server): ajoute route pour indicateurs dossiersApprenants ancien modèle

---

server/src/jobs/hydrate/organismes/hydrate-organismes-and-formations.js

Fix d'une anomalie dans l'hydrate des organismes / formations (thx to @Anne-Camille ) d'update non fait du siret de l'organisme lorsqu'il est remonté depuis le référentiel.

fix(server): update siret & sirets in hydrate-organismes-and-formations

---

.infra/ansible/env.ini

Plus besoin de backups sur le NAS pour la recette, c'était juste pour les tests.
TODO : une fois la PR validée

chore: remove nas backup for recette

---

server/src/common/model/next.toKeep.models/effectifs.model/effectifs.model.js
server/src/http/routes/specific.routes/serp.routes/upload.routes.js

Il y a des cas ou l'on ne peut ajouter un effectif car il existe déja un effectif identique mais avec un id_erp_apprenant différent.
En changeant l'index unique on devrait plus avoir le souci.
Voir avec @antoinebigard si lors de l'upload on rempli bien un id_erp_apprenant et si pas d'effets de bord

fix(server): update effectifs unique index using id_erp_apprenant

---

server/src/common/actions/engine/engine.actions.js
server/src/common/actions/engine/engine.organismes.utils.js

Fix de la fiabilisation, on ne settait pas la firstDate et la fonction de mapping des couples n'était pas bonne.
Avec ce fix, les données transmises sur un couple fiabilisé seront bien rattachées et l'organisme sera bien flaggé comme transmettant coté UI.
Une autre PR arrive pour le clean des organismes non fiables à supprimer (et effectifs / contributeurs liés à switcher)

fix(server): mapFiabilizedOrganismeUaiSiretCouple & setFirstTransmissionDate

---

server/src/jobs/cli.fiabilisation.js
server/src/jobs/fiabilisation/uai-siret/clean-organismes-non-fiables/index.js

Ajout du script de clean des organismes non fiables.
Pour chaque organisme non fiable, on switch ses effectifs sur l'organisme fiable rattaché, on append les contributeurs s'il y en a des nouveaux et enfin on le supprime.
Testé localement.
J'ai mis pas mal de logs pour bien identifier tout ce qui se passe.

chore(server): ajout du job de clean organismes non fiables

---

server/src/common/actions/dossiersApprenants.actions.js
server/src/common/actions/engine/engine.actions.js
server/src/http/routes/specific.routes/dossiers-apprenants.routes.js

Fix des historiques des dossiersApprenantsMigration et effectifs qui sont vides quand provenant de l'API.
3 Cas identifiés : 
- Création d'un dossier + effectif simple : on set l'historique avec un élement dans le tableau
- Maj du couple statut / date métier d'un dossier : on fait la maj dans l'update du dossierApprenantMigration
- Maj du couple statut / date métier d'un effectif : on fait la maj dans l'engine

fix(server): missing & empty historique_statut

---

server/src/common/actions/dossiersApprenants.actions.js
server/src/jobs/hydrate/reseaux/hydrate-reseaux.actions.js

Correction d'une anomalie lors de l'update de dossiers depuis l'hydrate des réseaux. 
Depuis l'hydrate l'objet fourni pour l'update n'a pas de statut (pas nécessaire) et l'historique était construit avec un élément vide, je garde l'historique initial désormais si aucun statut n'est fourni.

fix(server): hydrate new reseaux anomalie on update dossiers

---

.husky/commit-msg
.husky/pre-commit
package.json
rome.json
scripts/preventSensibleFilesCommit.sh
yarn.lock

la version 8 de husky a introduit des breaking changes.
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v8
J'ai aussi pluggé lint-staged avec rome, qui est beaucoup plus rapide, pertinent et user-friendly que prettier

fix: fix husky

---

server/src/common/actions/dossiersApprenants.actions.js
server/src/common/actions/engine/engine.organismes.utils.js
server/src/common/actions/organismes/organismes.actions.js
server/src/http/routes/specific.routes/dossiers-apprenants.routes.js

Correctif d'un cas bloquant lorsqu'on a une transmission d'un organisme qui ne fournit pas de siret : 
- Lors du structureDossierApprenant je récupère le siret de l'organisme si il a été fourni
- J'ajoute la gestion des siret null dans la fonction de search dans le mapping de fiabilisation
- Je gère les sirets non fournis dans le structureOrganismeFromDossierApprenant 
TODO : Update les tests unitaires pour tester : 
Une PR va venir s'ammender à ça pour gérer le 3e test unitaire et au lieu de throw une erreur, stocker dans la collection de fiabilisation ces cas particuliers pour analyse coté métier.

fix(server): handle organismes without siret in post

---

docker-compose.override.yml

- Désactive l'intégration Sentry en développement (A priori pas besoin ?) car cela bloque le démarrage de l'UI.
cf
- Désactive aussi Sentry du serveur pour rester cohérent.

fix: disable Sentry in development by default

---

server/src/common/utils/validationUtils.js
server/tests/data/randomizedSample.js

une petite PR pour fixer une erreur récurrente dans les tests concernant le format du SIRET + amélioration du message d'erreur affichée.
Les sirets utilisés sont les memes que dans le repertoire tests/data

fix: fix error on random sirets not following Luhn algorithm 

---

.github/workflows/_deploy.yml
.github/workflows/release-recette.yml

cette PR déploie automatiquement sur recette quand un nouveau commit est pushé dans master. La clé SSH utilisé est pour l'instant la mienne, mais on peut imaginer la mettre à jour plus tard pour utiliser un compte dédié.
Et voici un exemple de workflow run: https://github.com/mission-apprentissage/flux-retour-cfas/actions/runs/4135164772/jobs/7147352096
je ferais une PR dédiée pour mettre a jour le workflow de deploiement en prod

feat: deploiement automatique recette

---

.infra/ansible/roles/setup/files/app/tools/ssl/certbot/Dockerfile

Fix an issue with chalk requiring node ^12.17.0

fix: update certbot docker image

---

.infra/ansible/roles/setup/files/app/tools/cron-data-jobs/run-daily-jobs.sh
server/src/common/actions/organismes/organismes.actions.js
server/src/common/apis/apiReferentielMna.js
server/src/common/model/organismes.model.js
server/src/jobs/hydrate/organismes/hydrate-organismes-and-formations.js

Refacto & correction du job de récupération des organismes.
Plusieurs soucis identifiés qui impactent la fiabilisation des réseaux des organismes.
Une refacto & simplification du job.
Pour le moment pas d'optimisation de perf' mais à envisager par la suite.
- Refacto fonction de récupération d'infos depuis SIRET via API Entreprise 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/2584/commits/7e3472c01fd6355e35be297b6d3702d9867e21c1 (mutualisé car appelé depuis un job + depuis un composant)
- MAJ du modèle organisme pour couple UAI Siret unique via index 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/2584/commits/f3793e716169bd9f67c73a96a431af3bd75542f3
- Refacto fetchOrganismes avec options par défaut : 👉🏼 …

fix(server): hydrate organisme job & fiabilisation reseaux

---

ui/modules/mon-espace/effectifs/EffectifsPage.jsx
ui/pages/mon-espace/organisme/[id]/effectifs/index.jsx

un tout petit bug qui empeche un organisme avec mode_de_transmission = "API" de voir ses effectids apres la premiere transmission

fix: afficher les effectifs apres premiere transmission

---

server/migrations/20230210140629-remove-sirets-from-organismes.js
server/src/common/actions/engine/engine.actions.js
server/src/common/actions/organismes/organismes.actions.js
server/src/common/actions/permissions.actions.js
server/src/common/apis/apiReferentielMna.js
server/src/common/model/organismes.model.js
server/src/common/services/mailer/emails/validation_first_organisme_user_by_tdb_team.mjml.ejs
server/src/common/services/mailer/emails/validation_user_by_orga_admin.mjml.ejs
server/src/http/routes/specific.routes/espace.routes.js
server/src/http/routes/specific.routes/old/cfas.route.js
server/src/http/routes/specific.routes/organismes.routes.js
server/src/jobs/seed/start/index.js
server/tests/data/entreprise.api.gouv.fr/sampleDataApiEntreprise.js
server/tests/data/randomizedSample.js
server/tests/integration/common/actions/organismes.actions.test.js
server/tests/integration/http/dossiersApprenants.route.legacy.test.js
server/tests/integration/http/indicateurs.route.test.js
server/tests/integration/http/organismes.routes.test.js
ui/common/utils/stringUtils.js
ui/modules/mon-espace/landing/LandingOrganisme/components/OrganismeInfo.jsx
ui/pages/admin/users.jsx
ui/pages/mon-espace/mes-organismes.jsx

en WIP -> en cours de refactor de la fiabilisation des données.
A review commit par commit
Une fois déployé sur la recette / prod il faudra lancer les migrations mongo via 
`yarn migration:up`

chore(server): remove sirets array

---

server/src/http/routes/specific.routes/serp.routes/upload.routes.js
server/src/http/routes/specific.routes/server-events.routes.js
server/src/http/server.js
ui/hooks/useServerEvents.js
ui/modules/mon-espace/effectifs/Televersements.jsx
ui/modules/mon-espace/effectifs/engine/TransmissionFichier/components/UploadFiles.js

Cette PR ajoute un peu l'information de progression sur l'upload d'un fichier, avec le nombre de d'enregistrements traités, vs le nombre total. L'info transite sous forme de server events. On peut réutiliser ce canal pour une autre partie de l'app si besoin.
video: https://youtu.be/C0Hdc7R5j30

feat: ajout info progression upload

---

server/src/common/services/mailer/emails/templates.js
server/src/common/services/mailer/emails/validation_first_organisme_user_by_tdb_team.mjml.ejs
server/src/common/services/mailer/emails/validation_user_by_orga_admin.mjml.ejs
server/src/http/routes/user.routes/register.routes.js

Une PR qui fait suite a la PR https://github.com/mission-apprentissage/flux-retour-cfas/pull/2575, mais cette fois pour afficher les régions / academies / departement pour l'admin d'un organisme.
Related issue: https://github.com/mission-apprentissage/flux-retour-cfas/issues/2430
screenshot:

feat: affichage des régions dans l'email de validation de l'admin

---

server/src/common/actions/dossiersApprenants.actions.js
server/src/http/routes/specific.routes/indicateurs-national.routes.js
server/src/http/routes/specific.routes/indicateurs.routes.js

MAJ de la fonction de décompte des organismes transmettant leurs données au TDB.
Désormais un décompte sur les organismes id distinct sans prendre en compte la notion d'uai (car ils peuvent etre null)

fix(server): changement de la méthode de calcul du nb d'organismes transmettant au tdb

---

server/migrations/20230210140629-remove-sirets-from-organismes.js
server/migrations/20230210155720-set-default-fiabilisation-statut-organismes.js
server/migrations/20230210161055-set-default-fiabilisation-type-fiabilisationUaiSiret.js

Correction des migrations pour update les organismes ayant un siret.
Désormais le siret est obligatoire dans la collection organismes, vu avec @felixat13 on va analyser et supprimer les organismes sans siret qui n'ont plus rien à faire dans les données.

fix(server): correction des migrations en filtrant sur les organismes avec siret

---

.infra/ansible/roles/setup/files/app/.overrides/common/docker-compose.common.yml
.infra/ansible/roles/setup/files/app/.overrides/dev/docker-compose.env.yml
.infra/ansible/roles/setup/files/app/.overrides/production/docker-compose.env.yml
.infra/ansible/roles/setup/files/app/.overrides/recette/docker-compose.env.yml

Petite modification pour taper dans l'API de recette du référentiel si on est sur l'env de dev / recette.
Je supprime du common du coup et adapte la variable sur les 3 env

chore(infra): gestion de l'url du référentiel en recette / prod

---

.infra/ansible/roles/setup/files/app/.overrides/common/docker-compose.common.yml
.infra/ansible/roles/setup/files/app/.overrides/dev/docker-compose.env.yml
.infra/ansible/roles/setup/files/app/.overrides/production/docker-compose.env.yml
.infra/ansible/roles/setup/files/app/.overrides/recette/docker-compose.env.yml

Ceci n'est pas un troll, finalement il s'avère que l'environnement de recette du référentiel est "pourri" donc on reste branché sur la prod.
This reverts commit 1f998742e820d90732082c96068c24823f406079.

Revert "chore(infra): gestion de l'url du référentiel en recette / prod (#2605)"

---

server/src/common/actions/engine/engine.actions.js
server/src/common/actions/organismes/organismes.actions.js
server/src/common/model/organismes.model.js
server/src/http/routes/specific.routes/espace.routes.js
server/src/http/routes/specific.routes/serp.routes/upload.routes.js
server/src/jobs/cli.js
server/src/jobs/patches/update-lastTransmissionDates/index.js
server/tests/integration/common/actions/organismes.actions.test.js
ui/common/constants/fiabilisation.js
ui/pages/mon-espace/mes-organismes.jsx

Ajout d'un nouveau champ "date de dernière transmission" sur les organismes : 
- Ajout du champ au model 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/2634/commits/85b45cc0cd195602c5e0e951ea653034b84a062f
- Mise à jour de ce champ via API / Upload & Engine + tests 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/2634/commits/8b657386e5e5c56ae69f0dd1ceacca357a88243d
- Création d'un script pour initialiser les organismes existants 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/2634/commits/bc0ac590f22a75bb6b8a28363c24bdc25ee080d9
- MAJ du front (correction de constantes de fiab iso coté serveur + ajout date dernière transmission) 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/2634/commits/4f817bb76b2d26d0808a59351cacd …

chore: ajout de la date de dernière transmission des organismes

---

ui/next.config.js
ui/package.json
ui/pages/_app.jsx
ui/yarn.lock

il avait été supprimé lors de la migration vers nextjs
https://plausible.io/docs/nextjs-integration
Issue: https://github.com/mission-apprentissage/flux-retour-cfas/issues/2627

feat(ui): mise en place de plausible

---

server/src/common/actions/jobEvents.actions.js
server/src/common/constants/jobsConstants.js
server/src/jobs/cli.fiabilisation.js
server/src/jobs/cli.js
server/src/jobs/fiabilisation/uai-siret/apply-fiabilisation/index.js
server/src/jobs/fiabilisation/uai-siret/build-fiabilisation/index.js
server/src/jobs/hydrate/organismes/hydrate-organismes-referentiel.js
server/src/jobs/hydrate/organismes/hydrate-organismes.js
server/src/jobs/hydrate/organismes/update-organismes-with-apis.js
server/src/jobs/scriptWrapper.js
server/src/jobs/users/create-user.js

une PR pour revoir un peu le fonctionnement des scripts:
- utilisation du nom de la cmd pour le jobName pour éviter les erreurs de copier / coller (ex: la cmd "seed" utilisait Seed-admin)
- un seul jobEvent par run (sauf sur certains cas particuliers)
- log de l'exception rencontré dans runScript
- log systematique des datas renvoyé par l'action

refacfor(server): normalisation des calls a runScript

---

server/migrations/20230302000000-fix-admin-status.js
server/src/common/actions/users.actions.js
server/src/http/routes/user.routes/password.routes.js

- Quand un admin définit son mdp => passage en CONFIRMED directement.
- Micro-simplifications dans les contrôleurs express
- Migration pour rattraper les comptes admin dans un état incohérent (j'aurais pu modifier directement en base aussi...)

fix: fix admin account workflow

---

server/src/jobs/fiabilisation/uai-siret/build-fiabilisation/index.js

Reset de la table de fiabilisation avant le lancement du script.
On avait qqs reliquats de couples qui n'ont plus lieu d'être dans la table, le clear avant exécution devrait corriger ces soucis.

fix(server): clear fiabilisationUaiSiret before build

---

server/src/common/actions/dossiersApprenants.actions.js
server/src/common/actions/emails.actions.js
server/src/common/actions/engine/engine.actions.js
server/src/common/actions/organismes/organismes.actions.js
server/src/common/actions/organismes/organismes.formations.actions.js
server/src/common/actions/permissions.actions.js
server/src/common/actions/roles.actions.js
server/src/common/actions/sifa.actions/sifa.actions.js
server/src/common/actions/uploads.actions.js
server/src/common/actions/users.actions.js
server/src/common/mongodb.js
server/src/http/routes/admin.routes/users.routes.js
server/src/http/routes/specific.routes/dossiers-apprenants.routes.js
server/src/http/routes/specific.routes/effectif.routes.js
server/src/http/routes/specific.routes/organismes.routes.js
server/src/http/routes/specific.routes/serp.routes/upload.routes.js
server/src/jobs/fiabilisation/dossiersApprenants/analyse-fiabilite-dossiers-apprenants-recus.js
server/src/jobs/hydrate/archive-dossiers-apprenants/hydrate-archive-dossiersApprenants.js
server/src/jobs/hydrate/reseaux/hydrate-reseaux.js
server/src/jobs/seed/start/index.js
server/tests/integration/common/actions/organismes.actions.test.js
server/tests/integration/common/actions/users.legacy.actions.test.js
server/tests/integration/http/dossiersApprenants.route.legacy.test.js

- Ajout du type MongoClient au mongoClient global dans `server/src/common/mongodb.js`
Désormais, le type est propagé dans toutes les fonctions qui utilisent du Mongo. En revanche, le typage des documents récupérés / mis à jour est toujours en any.
- Quelques corrections faites pour du code en erreur

chore: add type for MongoClient + lint

---

server/src/http/routes/specific.routes/old/referentiel.route.js
server/tests/integration/http/referentiel.route.test.js

Vu avec Anne, on ne doit pas afficher les réseaux non fiables dans le filtre.
Fix temporaire, on ne stock pas l'info de la fiabilité d'un réseau donc on passe par une const pour l'instant.

chore(server): récupération des réseaux fiables uniquement

---

.infra/ansible/roles/setup/files/app/.overrides/common/docker-compose.common.yml

Le docker-compose.common.yml semble utilisé pour les environnements déployés. J'ai juste décommenté pour rendre obligatoire l'authentification pour chaque connexion.
Les utilisateurs admin, user, metabase et backup existent déjà et sont déjà bien configurés en principe.

fix: require mongodb authentication

---

server/migrations/20230309120000-remove-unused-fields.js
server/migrations/20230309150000-update-account-status.js
server/migrations/20230313000000-fix-wrong-organisme-no-uai.js

ByPass de la validation sur l'update des 3 dernières migrations.
A discuter ensemble sur le mécanisme le plus propre à retenir pour gérer les migrations de données et/ou de schéma avec validation

fix(server): bypass validation on migrations

---

server/src/common/actions/organismes/organismes.actions.js
server/src/jobs/fiabilisation/uai-siret/apply-fiabilisation/index.js

MAJ du script de fiabilisation suite au pt avec Anne / Félix : suppression des organismes non fiabilisables (mapping) et leurs dossiersApprenants / effectifs après avoir corrigé les effectifs sur le bon organisme fiable.
Ajout de la fonction de delete d'un organisme et ses effectifs / dossiersApprenants liés dans les actions si besoin de la réutiliser (ca sera le cas dans la suite des étapes de fiabilisation)

chore(server): suppression des organismes (& effectifs/dossiersApprenants liés) non fiabilisables mapping

---

server/package.json
server/src/common/actions/formations.actions.js
server/src/common/actions/infoSiret.actions.js
server/src/common/actions/organismes/organismes.actions.js
server/src/common/actions/organismes/organismes.formations.actions.js
server/src/common/apis/ApiCfaDock.js
server/src/common/apis/apiCatalogueMna.js
server/src/common/logger.js
server/src/config.js
server/tests/integration/common/actions/organismes.actions.test.js
server/tests/integration/common/actions/users.legacy.actions.test.js
server/tests/integration/http/dossiersApprenants.route.legacy.test.js
server/tests/integration/http/indicateurs.route.test.js
server/tests/integration/http/organismes.routes.test.js
server/tests/utils/nockApis/nock-apiCatalogue.js
server/yarn.lock

Quelques améliorations découvertes pendant mon investigation sur #2734.
A noter que `createOrganisme()` est systématiquement appelé avec les paramètres.
```js
{
buildFormationTree: false,
buildInfosFromSiret: false,
callLbaApi: false,
}
```
Seul `updateOrganisme()` est appelé avec ces paramètres à true (aussi valeur par défaut...) lors du job `update:organismes-with-apis`. Donc pas mal de duplication / code mort :(

chore: petit lot d'améliorations

---

server/src/common/model/usersMigration.model.ts
server/src/common/validation/userSchema.ts
ui/modules/admin/UserForm.jsx
ui/modules/admin/userSchema.js
ui/package.json
ui/yarn.lock

fix #2593
J'utilise maintenant le meme schema Zod coté backend et frontend pour harmoniser les validation, et à terme mettre en commun dans un dossier partagé. 
Petit bemol, j'ai été obligé de supprimer la validation Joi  au niveau du schema de données, parce qu'elle teste aussi l'email, avec des regles plus strictes (en particulier, Joi teste si le tld existe).

2593 création dun utilisateur par ladmin rendre plus clair le message derreur en cas dinvalidité dun des champs

---

server/src/common/actions/dossiersApprenants.actions.ts
server/src/common/actions/effectifs/effectifs.actions.ts
server/src/http/routes/specific.routes/indicateurs-national.routes.ts

Je propose de baser le calcul du nb d'organismes distinct en se basant sur la collection effectifs (la collection dossiersApprenantsMigration est vouée à disparaitre).
Déplacement de la méthode dans effectifs.actions.js.

fix(server): replacement de getNbDistinctOrganismes en se basant sur la collection effectifs

---

server/src/jobs/fiabilisation/uai-siret/build-fiabilisation/index.ts

MAJ de la récupération des couples UAI-SIRET à fiabiliser depuis la collection effectif (via lookup organismes) vu que la collection dossiersApprenantMigration est vouée à disparaitre.
Après analyse cela va nous permettre de fiabiliser encore plus nos chiffres :)

fix(server): fiabilisation : récupération des couples UAI-SIRET depuis les effectifs lookup organismes

---

server/src/common/apis/apiReferentielMna.ts
server/src/common/model/organismesReferentiel.model.ts
server/src/jobs/hydrate/organismes/hydrate-organismes-referentiel.ts

Ajout des lieux de formation dans les organismes du référentiel.
Sera utile pour faire un match sur les uai des lieux de formation afin de poursuivre la fiabilisation des couples UAI SIRET que l'on a versus ce qu'on trouve dans le référentiel.

chore(server): add lieux de formation to organismesReferentiel

---

server/src/common/actions/emails.actions.ts
server/src/common/actions/engine/engine.actions.ts
server/src/common/actions/organismes/organismes.actions.ts
server/src/common/actions/uploads.actions.ts
server/src/common/actions/users.actions.ts
server/src/common/mongodb.ts
server/src/http/routes/specific.routes/organismes.routes.ts
server/src/http/routes/specific.routes/serp.routes/upload.routes.ts
server/src/jobs/fiabilisation/dossiersApprenants/analyse-fiabilite-dossiers-apprenants-recus.ts
server/src/jobs/hydrate/archive-dossiers-apprenants/hydrate-archive-dossiersApprenants.ts
server/src/jobs/hydrate/reseaux/hydrate-reseaux.ts
server/tests/integration/common/actions/formations.actions.test.ts

Petite PR pour restaurer le type sur le mongoClient pour avoir le typage sur toutes les requêtes qui en découlent.
J'en ai besoin pour mon refacto des permissions :smiley:

fix: restauration typage client mongo

---

server/package.json
server/src/jobs/fiabilisation/uai-siret/apply-fiabilisation/index.ts

Correction du script de fiabilisation car il y avait certains cas d'organismes non fiables qui restaient en base.
1. Une partie qui n'étaient pas supprimés sont sans SIRET et non fiabilisables (mapping), à cause de la validation mongodb il n'étaient pas mis à jour
2. D'autres dans le flow des A FIABILISER, on ne supprimait pas les organismes non fiables.
- Petit correctif sur la commande de lancement des tests avec le cross-env en premier (je suis sous Windows 🥲) 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/2793/commits/f1d1361e8dd601ff6ce33b7125489b41ad7bccd6
- Ajout du byPassValidation pour MAJ des organismes sans siret afin de les identifier comme Non Fiabilisables Mapping et de les supprimer ensuite 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/ …

fix(server): fiabilisation - suppression des organismes non fiables

---

.infra/ansible/roles/setup/files/app/.overrides/production/docker-compose.env.yml
.infra/ansible/roles/setup/files/app/.overrides/recette/docker-compose.env.yml

Sur prod et recette, comme les agents sont recréés à chaque déploiement. De nouveaux conteneurs sont recréés et les dashboard actuels utilisent le nom d'hôte /etc/hostname (= id du conteneur par défaut) pour identifier l'hôte à monitorer.
Avec cette PR, on surcharge l'hôte dans la configuration des conteneurs nodeexporter et cadvisor.
Il faudra encore faire un setup-vm une fois la PR mergée. :)

fix: hostname des agents de monitoring

---

server/src/common/model/@types/Organisme.ts
server/src/common/model/@types/OrganismesReferentiel.ts
server/src/common/model/organismesReferentiel.model.ts
server/src/jobs/fiabilisation/uai-siret/build-fiabilisation/index.ts
server/src/jobs/hydrate/organismes/hydrate-organismes.ts

Ajout de la récupération de la notion d'uai fiable dans le référentiel et update du script pour ne matcher que sur les uai fiables.
Fix de la property qualiopi (certains organismes n'ont pas le champ dans le référentiel)

fix(server): fiab sur uai lieux fiables + fix qualiopi hydrate

---

Makefile
server/.yarnrc
server/.yarnrc.yml
server/package.json
server/src/common/utils/cryptoUtils.ts
server/src/http/middlewares/helpers.ts
server/src/http/middlewares/validateRequestMiddleware.ts
server/src/http/routes/specific.routes/organisme.routes.ts
server/src/http/server.ts
server/src/jobs/fiabilisation/dossiersApprenants/process-effectifs-queue.ts
server/tests/utils/permissions.ts
server/tsconfig.json
server/yarn.lock

Une PR pour pouvoir utiliser les paths dans tsconfig, sur la partie server. J'ai été obligé de passer sur tsx, qui supporte bcp mieux cela que ts-node.
J'en ai profité pour ajouté express-list-endpoints pour lister toutes les URLs sur le server express (il y en a bcp, du coup on s'y perd un peu).

chore: migration de ts-node vers tsx

---

server/src/common/actions/helpers/permissions.ts

Corrige un findOne basé uniquement sur le siret (car non unique).

fix: lien entre organismes avec uai et siret

---

server/src/common/actions/formations.actions.ts
server/src/common/actions/organismes/organismes.formations.actions.ts
server/src/common/apis/apiCatalogueMna.ts
server/src/common/model/organismes.model.ts
server/tests/integration/common/utils/miscUtils.test.ts

#2521 
PR minimale avec un nouveau champ dans organismes.relatedFormations[].
Je ne touche pas du tout à la collection formations, qu'on pourra peut-être supprimer après les futurs dashboards d'indicateurs.
Il faudra attendre que le job `update:organismes-with-apis` soit exécuté pour avoir les données à jour. (toutes les nuits) 
---
Mis en pause en attendant d'avoir plus d'informations sur les spécifications.
L'objectif dans le futur est de pouvoir proposer une route pour retourner par exemple la liste des apprentis sans contrat sur la région PACA avec email + avec clé ministère (il faut donc pouvoir lier la clé ministère et l'effectif)
Les formations (collection formations) ne sont créées qu'à l'ajout/mise à jour des organismes.
Après discussion avec @antoinebigard, il apparait que notre …

feat: ajout du champ cle_ministere_educatif dans formations

---

docker-compose.yml

Proposition d'upgrade de la memlimit du server.
J'ai constaté que le job hydrate:organismes dépasse le quota 2G depuis qqs jours sur la prod / recette. Il y a peut etre une alternative à creuser ensemble

chore(server): upgrade mem limit

---

docker-compose.override.yml
docker-compose.yml

Au démarrage de mon PC, la stack n'est jamais correctement démarrée entre autres car nginx se vautre car le smtp n'est pas démarré.
Cette PR corrige les politiques de restart des conteneurs pour unless-stopped (qui est safe à utiliser partout)

fix: démarrage automatique des services en dev

---

server/src/common/actions/engine/engine.actions.ts
server/src/common/actions/organisations.actions.ts
server/src/common/constants/territoires.ts
server/src/common/model/effectifs.model/effectifs.model.ts
server/src/common/model/json-schema/adresseSchema.ts
server/src/common/model/organisations.model.ts
server/src/common/utils/adresseUtils.ts
ui/common/constants/territoires.ts
ui/components/CfasFilter/CfasList.tsx
ui/components/TerritoireFilter/TerritoireFilter.tsx
ui/components/TerritoireFilter/TerritoireList.tsx
ui/modules/auth/inscription/InscriptionOperateurPublic.tsx
ui/pages/auth/inscription/profil.tsx
ui/pages/par-territoire.tsx

- synchronisation des 2 fichiers UI et server (quelques trucs supplémentaires dans UI toutefois)
- utilisation de _BY_CODE partout plutôt que _BY_ID
- correction d'un `adresseInfo.num_academie.toString()` qui échouait si `adresseInfo.num_academie === undefined`
- suppression des clés académies avec padding 01, car on utilise toujours la version sans padding. (les données number viennent des TCO). En base, on est sur des strings qui contiennent des entiers. C'est pas génial, mais ça marche et y'a 10 fois pire ailleurs... :smile:

fix: network constants

---

server/src/commands.ts
server/src/jobs/fiabilisation/dossiersApprenants/remove-nonRecus-depuis/index.js

Ajout d'un script de suppression des inscrits sans contrats depuis 90 jours par défaut.
Avant de l'exécuter en prod il faudra que @nadinelouchart affiche un bandeau coté métier pour prévenir de la suppression de 13K+ effectifs correspondants.

chore(server): script de suppression des inscrits sans contrats non recus depuis X semaines

---

ui/modules/auth/inscription/InscriptionOperateurPublic.tsx

Suite à demande @cathbaiona :
Les données sont triées par code région, or on affiche que le label ce qui n'aide pas à comprendre la logique de tri.
Pas besoin de code pour les régions / académies car le code est moins connu et il y a moins de données.

feat: affichage du code département à l'inscription

---

ui/modules/indicateurs/NatureOrganismeTag.tsx

J'avais encore le problème sur mon poste, maintenant c'est bon tout le temps.

fix(ui): en cas d'absence de nature d'organisme, le texte inconnu pouvait passer sur deux lignes

---

ui/components/Page/components/Header.tsx
ui/modules/indicateurs/IndicateursForm.tsx

feat: filtrage bassins emploi pour dreets

---

.github/workflows/ci.yml

Suppression du déploiement en recette en attendant d'avoir un déploiement sans downtime pour éviter les interruptions de services sans dégrader le devxp (push master OK)
cc @antoinebigard @totakoko

chore(ci): suppression du déploiement en recette pour éviter les interruptions de services

---

server/src/common/actions/indicateurs/indicateurs.actions.ts
ui/modules/dashboard/CarteFrance.tsx
ui/modules/dashboard/DashboardTransverse.tsx
ui/modules/dashboard/IndicateursGrid.tsx

See: https://www.notion.so/mission-apprentissage/Feedbacks-User-Research-Juin-e08663e783f04dfc890de4d53a9c145d
Liste des actions : 
- Nouveau calcul "apprenant"
- [Amélioration] Cartographie du taux de couverture : rajouter %
- Tooltip à préciser “Taux de couverture”
- Phrase à changer “Ces chiffres reflètent…” selon maquette

fix: corrections mineures sur les indicateurs et nouveau calcul sur les apprenants

---

ui/modules/indicateurs/IndicateursForm.tsx

J'ai repris le texte du figma, mais j'ai adapté : `pour les jeunes sans contrat` en `pour les jeunes en formation sans contrat` (cf conversations précédentes) et `sorties` (faute d'accord afaik) en `sortis d’apprentissage`. Je peux changer les textes si besoin.

fix: changement de texte pour les indicateurs

---

ui/pages/auth/inscription/profil.tsx

Auparavant, la règle de 20c pour les admins était appliquée, mais pas affichée.

fix: affichage longueur min 20c pour les admins

---

server/src/common/actions/engine/engine.organismes.utils.ts
server/src/jobs/fiabilisation/uai-siret/build.rules.ts
server/tests/integration/common/actions/engine.organismes.utils.test.ts
server/tests/integration/jobs/fiabilisation/uai-siret/build-fiabilisation-uai-siret.test.ts

Petite PR de refacto / mutualisation de la logique de vérification d'un organisme fiable via un couple UAI SIRET.
MAJ coté script de fiabilisation + tests

chore(server): refacto vérification organisme fiable

---

ui/modules/indicateurs/IndicateursForm.tsx

Problème remonté par Nadine : Cela n'a pas de sens d'afficher le filtre réseau pour une tête de réseau.

fix: cacher filtre réseau pour les têtes de réseau

---

ui/modules/models/graphs.test.ts
ui/modules/models/graphs.ts

Vu avec @felixat13, quickfix pour positionner la borne minimale à zéro car les utilisateurs s'y perdent.
Plus tard, éventuellement, on pourra changer la façon dont les bins sont créés.

fix: borne min à 0 pour l'échelle des cartes

---

server/src/jobs/seed/plausible/goals.ts
ui/common/plausible-goals.ts
ui/components/Links/Link.tsx
ui/components/Page/components/Header.tsx
ui/components/Page/components/NavigationMenu.tsx
ui/pages/index.tsx

https://tableaudebord-apprentissage.atlassian.net/browse/TM-10
Contenu :
- nettoyage des goals obsolètes
- tracking des boutons de la page d'accueil (+ menus globaux)
- ajout d'interfaces TS pour s'assurer qu'on nomme bien les gloals.
- je n'ai pas touché à la page stats qui construit les événements dynamiquement, donc embêtant pour TS.
Idéalement, Félix aurait voulu tracker l'utilisation de la carte sur la page d'accueil, avec comme définition : si on affiche les popups de départements pendant au moins 5 secondes, alors on envoie un événement.
=> Pas réalisé car c'est plus long à développer

feat: ajout tracking plausible page d'accueil

---

ui/modules/indicateurs/NewTable.tsx

J’ai une solution _(à l’arrache potable)_ pour le hover de la table

fix(ui): ajout d'un hover sur les tables

---

server/src/common/actions/sessions.actions.ts
server/src/common/model/internal/AuthContext.ts
server/src/common/utils/jwtUtils.ts
server/src/http/helpers/passport-handlers.ts
server/src/http/routes/user.routes/auth.routes.ts
server/src/http/server.ts
server/tests/integration/http/impersonation.routes.test.ts
ui/common/httpClient.ts
ui/common/internal/AuthContext.ts
ui/components/Page/components/Header.tsx
ui/pages/admin/impostures.tsx
ui/theme/components/icons/ExitIcon.tsx
ui/theme/components/icons/SpyLine.tsx

Pour remédier à la problématique de comptes de test (recette et prod) qui impactent les autres utilisateurs.
- nouvelle entrée dans le menu utilisateur
- nouvelle page impostures, avec des boutons prédéfinis pour changer ton organisation
- des petites retouches au niveau des jwt qui font office de token de session (en moins bien...)
Notes :
- Je n'ai pas pu tester par manque de temps les fonctionnalités avancées en tant qu'OF...

feat: imposture d'organisations

---

ui/modules/indicateurs/filters/FiltreOrganismeBassinEmploi.tsx
ui/modules/indicateurs/filters/FiltreOrganismeTerritoire.tsx

cf: https://mission-apprentissage.slack.com/archives/C05BYDX2CMB/p1686904818924419 et https://tableaudebord-apprentissage.atlassian.net/browse/TM-72

fix(ui): remplacer bassin d'emploi par zone d'emploi à l'affichage seulement

---

ui/common/domain/siret.ts
ui/modules/auth/inscription/components/SearchBySIRETForm.tsx

Selon le commentaire, on cherchait à se débarasser de cette regex.
J'ai vu qu'elle était utilisée à un seul endroit dans un formik (side note : je déteste formik, chaud pour en parler !) et que c'était pour rechercher donc on s'en fiche du changement très léger de fonctionnement

chore: suppression de siret_regex qui semble obsolete et utilisé à un seul endroit

---

ui/common/SSR/getAuthServerSideProps.ts
ui/common/SSR/isInitialServerSideProps.ts

Comme la fonction est interne et utilisée seulement là, ça me semble plus simple à lire

chore: suppression d'un fichier pour une fonction interne

---

ui/components/InfoTooltip/InfoTooltip.tsx

Le composant était clairement dupliqué. Pour info, `InfoCircle`:
```jsx
export function InfoCircle(props) {
return (
<Icon viewBox="0 0 24 24" w="15px" h="15px" {...props}>
<path
d="M12 22C6.477 22 2 17.523 2 12C2 6.477 6.477 2 12 2C17.523 2 22 6.477 22 12C22 17.523 17.523 22 12 22ZM12 20C16.4183 20 20 16.4183 20 12C20 7.58172 16.4183 4 12 4C7.58172 4 4 7.58172 4 12C4 16.4183 7.58172 20 12 20ZM11 7H13V9H11V7ZM11 11H13V17H11V11Z"
fill="currentColor"
/>
</Icon>
);
}
```

chore: suppression d'un composant dupliqué

---

ui/modules/mon-espace/effectifs/EffectifsBanner.tsx
ui/modules/mon-espace/effectifs/EffectifsPage.tsx

https://tableaudebord-apprentissage.atlassian.net/browse/TM-29
- En local je n'ai pas d'effectifs, donc c'est très mal testé
- J'espère avoir bien compris le pb. L'idée c'est : j'affiche les effectifs même si je n'ai pas les infos de mode de transmission à partir du moment où j'ai transmission.

fix(ui): affichage des effectifs quand ils ont été importés au moins une fois (tm-29)

---

.infra/ansible/roles/setup/files/app/.overrides/common/docker-compose.common.yml

corrige un bug lié aux dashboard avec paramètres
Dans la [doc de metabase](https://www.metabase.com/docs/latest/installation-and-operation/upgrading-metabase), il est indiqué qu'on peut (va ?) perdre les données comme on a pas de production database.
A priori, comme on a un volume monté sur `/metabase-data` je dirais que tout va bien. :)

fix: maj metabase vers v0.46.6

---

server/.env.test
server/src/config.ts
server/src/http/server.ts

L'idée c'est que si on envoie 50 apprenants ça fait un payload too high
D'ailleurs ça m'étonne que ça marchait pour tout le monde avec 100kb c'est vite atteint non @totakoko & @sbenfares ?

chore: incrementation de la limite d'envoi json pour l'API en restant raisonnable quand même

---

server/src/common/actions/helpers/permissions.ts

- En regardant les relations entre OF via les formations, je suis retombé sur la fonction `findOFLinkedOrganismesIds` (qu'on devrait sans doute mettre à jour au passage pour s'assurer qu'on ne liste que les organismes formateurs).
J'avais fait une modificaiton il y a quelque temps pour rechercher sur le couple UAI + SIRET (clé d'unicité), plutôt que juste sur le SIRET. mais en relisant, je pense avoir foiré la condition car elle exclue les organismes avec même UAI ou même SIRET... Cette PR corrige ça.
- Et aussi une recherche d'un organisme avec les infos de l'organisation. Idem il faut utiliser le siret et l'uai (même s'il n'est pas défini = null)
En bonus, est-ce que ça ne vaudrait pas le coup de définir plus spécifiquement ce qu'on recherche ? Cad ici les organismes qui dispensent des …

fix: correction condition liste des organismes liés

---

server/src/common/actions/organismes/organismes.actions.ts
ui/hooks/organismes.ts
ui/modules/organismes/OrganismesTable.tsx

- Complète la nature des organismes côté UI (300 organismes concernés), pour que nature INCONNUE se comporte de la même façon que nature null. Idéalement, ça serait à faire dans une migration pour corriger les données, mais je n'ai aucune assurance qu'il n'y a pas un bout de code quelque part qui ne crée pas des organismes sans nature. (je pense notamment à l'inscription avec une organisme de l'api entreprise uniquement)
- Ajoute une mention INCONNUE en rouge en face d'un UAI manquant dans la liste des organismes.
- ~En attente Nadine au cas où il faille trier différemment la colonne nature pour mettre les inconnues en début ou fin de liste plutôt qu'au milieu.~ => j'ai pris l'initiative de déplacer les natures inconnues en début de liste en cas de tri

Ameliorations page organismes

---

server/src/http/routes/specific.routes/dossiers-apprenants.routes.ts

Actuellement, si l'insertion en db échoue dans effectifsQueue, on renvoie une 500 sans infos:
```
{
"status": "ERROR",
"message": "Document failed validation"
}
```
Étant donné qu'on n'est pas encore sûr d'être carré entre nos contrôles côté Zod et nos blocages côté mongodb, j'ai une proposition. Cette PR contient des opinions, tout est discutable : 
- Etant donné que la seule erreur du try/catch est liée à l'insertion des données qui échoue, je pense qu'on peut balancer une 400 (car elles sont mal formées)
- Je pense qu'on peut faire suivre l'erreur au client sans risque étant donnée que : 
1. On est en exploration sur la compréhension de notre modèle
2. Notre code est open source donc notre modèle est public
3. On gagne à avoir les infos des erreurs de nos clients direct pour gagner du …

chore: plus d'infos quand une erreur arrive côté mongodb

---

server/migrations/20230727114445-fix-effectifs-contrats.js
server/migrations/20230727114600-fix-effectifs-annee-formation.js

Ajout de 2 migrations pour correction du format des effectifs sur des cas que j'ai identifiés : 
- champ contrat null au lieu de []
- annee de la formation en string

chore(server): ajout de migration pour correction des effectifs

---

server/src/common/actions/organismes/organismes.actions.ts
server/src/jobs/fiabilisation/uai-siret/build.ts
server/src/jobs/ingestion/process-ingestion.ts

- Dans l'ingestion prise en compte de la récupération des couples fiabilisés par le scripts de fiabilisation.
- Dans le script de fiabilisation, on récupère désormais tous les couples du TDB ainsi que les couples valides dans la queue.
Pour les exemples AFTRAL qui ne transmettent plus, ce correctif va en 3 temps : 
- Ingérer la donnée, ne pas trouver d'organisme fiable lié donc conserver dans la queue la donnée en erreur
- Au lancement du script de fiab, on va désormais prendre le couple AFTRAL qui est dans la queue en erreur, et le fiabiliser avec le référentiel -> l'ajouter à la collection fiabilisationUaiSiret
- A la prochaine ingestion, vu que le couple est à fiabiliser dans fiabilisationUaiSiret, on va désormais pouvoir le trouver et donc intégrer la donnée au tdb ✅

fix(server): correction de l'ingestion et des scripts de fiabilisation

---

.infra/ansible/roles/setup/files/app/.overrides/common/docker-compose.common.yml

cf. https://www.metabase.com/blog/security-advisory-h2

chore: upgrade metabase 0.46.6.4

---

server/src/jobs/ingestion/process-ingestion.ts

:zap: 
Actuellement si la queue contient 2.5M effectifs à traiter, le count met ~ 10 secondes, donc on le supprime.
(théoriquement, on devrait quand même arriver à traiter les effectifs plus rapidement qu'ils n'entrent...ça n'a pas toujours été le cas !)

perf: suppression du count total des effectifs dans la queue

---

ui/components/Page/components/NavigationMenu.tsx

Catherine trouvait la police de la deuxième trop grosse et elle n'a pas tort, voilà j'ai mis la même taille partout

chore(ui): harmonisation de la taille dans la subnavbar

---

server/src/common/utils/stripNullProperties.ts
server/src/http/routes/specific.routes/dossiers-apprenants.routes.ts
server/tests/data/randomizedSample.ts

Suite à discussion avec SCForm : 
Ils envoient tous leurs objets formatés pareil, avec des null quand ils n'ont pas la valeur.
Pour éviter de péter une erreur Zod dans l'envoi en queue on va "simplement" stripper tous les champs null avant d'envoyer.
La prise de risque parait faible, le seul cas serait une réinitialisation de données voulue.
Si les tests passent je pense qu'on peut dire que c'est bon

fix: remove null properties before zod validation and sending to queue

---

server/migrations/20230720093700-update-est-dans-referentiel-flag.js
server/src/common/constants/organisme.ts
server/src/common/model/@types/Organisme.ts
server/src/common/model/organismes.model.ts
server/src/jobs/fiabilisation/uai-siret/update.ts
server/src/jobs/hydrate/organismes/hydrate-organismes.ts
server/src/jobs/hydrate/reseaux/hydrate-reseaux.ts
server/tests/utils/permissions.ts
ui/common/internal/Organisme.ts
ui/modules/admin/OrganismeDetail.tsx
ui/modules/admin/OrganismesList.tsx

Objectif : identifier les organismes du référentiel avec uai multiples dans le TdB.

chore(server): transformation du champ est_dans_referentiel

---

server/src/commands.ts
server/src/jobs/fiabilisation/uai-siret/build.ts
server/src/jobs/fiabilisation/uai-siret/build.utils.ts
server/src/jobs/hydrate/organismes/hydrate-organismes.ts

Déplacement de la fonction de reset des statuts de fiabilisation des organismes dans le job de build de la fiabilisation.

chore(server): move reset statut fiab

---

server/tests/data/randomizedSample.ts

Dû à https://github.com/mission-apprentissage/flux-retour-cfas/pull/3128. Il doit maintenant y avoir un stripUndefined pour supprimer les valeurs non définies. Je fais en sorte d'avoir toujours le champ periode_formation défini.
Si on veut du random, ça sera pour un test bien précis. C'est mieux d'isoler les données pour les tests.

fix: flaky test

---

server/src/common/actions/organismes/organismes.actions.ts
server/src/http/routes/specific.routes/upload.routes.ts
server/src/jobs/ingestion/process-ingestion.ts
server/tests/integration/common/actions/organismes.actions.test.ts

Suite au refactor de l'ingestion + monitoring, j'avais modifié cette partie pour ne mettre à jour que la date de dernière transmission.
Ici je rétablis aussi celle de 1ère tranmission, qui est potentiellement utilisée mais jamais affichée.
Selon moi, last_transmission_date est beaucoup plus intéressant que first_transmission_date pour connaître si un organisme a transmis des effectifs.

fix: maj first_transmission_date en même temps que last_transmission_date

---

server/src/jobs/fiabilisation/uai-siret/build.ts

Petit (mais important) fix sur la requête de récupération des couples de la queue pour la fiabilisation.
Le filtre sur validationErrors empéchait d'avoir dans la liste des couples à fiabiliser (vu qu'ils ont une erreur ils ne remontent pas et ne peuvent pas donc être fiabilisés hors c'est ce qu'on souhaite)

fix(server): fiabilisation effectifQueue sans filtre sur validation

---

ui/modules/dashboard/DashboardTransverse.tsx

Source : 
Et: https://www.figma.com/file/0mofiw6xvEKFnvdIjl5Whl/DSFR-x-TdB?type=design&node-id=345%3A71736&mode=design&t=iwhKUWG4XsXP0GlH-1

chore: add tooltip national

---

server/src/common/actions/organismes/organismes.actions.ts

Corrige le problème remonté par Raph / Antoine concernant l'api key.
Celle-ci n'était plus retournée côté UI suite aux modifications des permissions (pour éviter que tout le monde n'ait accès à ces infos sensible).
Problème initial :
> Tu te connectes en tant que quelqu’un (n’importe qui) et tu vas sur “mon compte” => “paramétrage ERP” et là ya le bouton qui apparait et ça devrait t’envoyer sur la page en question et si tu clique sur “générer la clé” tu as rien alors que tu avais quelque chose
Par contre en regardant le code, j'ai vu plusieurs problèmes :
- Déjà l'onglet paramétrage ERP est dans mon-compte, et devrait être au niveau de l'organisme. Le problème est qu'un utilisateur non OF peut accéder à cette page et obtient une page blanche comme il n'a pas d'organisme...
- Il y a une …

fix: retourne api_key & cie selon les droits

---

server/src/jobs/fiabilisation/uai-siret/build.ts

Correctif du script de fiabilisation : on a besoin de passer aux règles de fiab la liste des couples UAI-SIRET présents dans le TdB et dans le référentiel et on lui passait la liste des couples dans le TDB + dans la queue.
Il se peut donc qu'on n'arrive pas à fiabiliser car cette liste était trop grosse et on peut avoir zappé des validation de la regle de siret/uai unique dans le TDB à case de ça.

fix(server): correction du passage de la liste des couples du TDB vs couples Queue + Tdb

---

.github/workflows/preview.yml
server/tests/jest/setupMongo.ts

C'était un peu trop gros, trop d'emphase tue le(s) message(s)

chore: réduction de la taille du message de branche de prévisualisation

---

server/src/common/constants/validations.ts
server/src/common/validation/utils/zodPrimitives.ts

Un ERP et un téléversement manuel ont fait l'erreur d'envoyer la clé dans le NIR donc on se dit qu'on peut réparer silencieusement (donc on accepte 15 caractères aussi et on retire les deux derniers)

fix(server): on accepte maintenant le NIR avec 13 ou 15 caractères

---

server/src/http/server.ts

Contexte : On retire les valeurs nulles dans l'import API v3/v2 pour ne pas avoir de bugs quand les ERPs envoient une donnée null juste pour pas l'envoyer (vu en direct avec SCForm qui fonctionne comme ça).
Maintenant on fait la même chose pour la validation de l'import excel sinon c'est incohérent. Et surtout parce que des valeurs nulles peuvent arriver !

chore: retrait des valeurs nulles de la validation Excel pour être cohérent avec l'import réel

---

server/src/commands.ts
server/src/jobs/hydrate/organismes/hydrate-organismes.ts
server/src/jobs/jobs.ts
server/src/jobs/patches/remove-organismes-absentReferentiel-sansTransmission/index.ts

2 correctifs : 
- Un script de suppression des organismes non fiables (absent du référentiel) n'ayant jamais transmis, ce sont des organismes reliquats de l'ancienne version du TDB (Janvier 2023), il n'ont pas d'utilité.
- Un fix dans l'hydrate des organismes, pour marquer comme FIABLE les organismes présents dans le référentiel, ayant une UAI et encore ouverts. 
Vu que le script de fiabilisation se base sur la liste des organismes liés à des effectifs, les organismes ne transmettant pas mais étant fiables n'avait jamais de statut de fiabilisation mis à jour.

chore(server): suppression des organismes absents du referentiel n'ayant jamais transmis + fix organismes fiables

---

ui/modules/mon-espace/effectifs/doublons/EffectifDoublonDeleteAlertDialog.tsx
ui/modules/mon-espace/effectifs/doublons/EffectifsDoublonsList.tsx
ui/modules/mon-espace/effectifs/doublons/EffectifsDoublonsPage.tsx

Quelques correctifs sur la page des doublons : 
- Suppression d'un id inutile
- Désactivation du tri
- Suppression d'un bouton inutile
Autre souci bizarre en prod le reload ne se fait pas.

fix(ui): correctifs page des doublons

---

jest-mongodb-config.js
jest.config.js
package.json
server/package.json
server/tests/jest/globalSetup.ts
server/tests/jest/globalTeardown.ts
server/tests/utils/mongoUtils.ts
yarn.lock

Il me semble qu'il y a des soucis lors du téléchargement de la mongo memory serveur alétoirement. 
Je penses que comme c'est fait en parallel et ça overwrite le fichier cible ça crée des conflits. La lib recommandé par jest est un wrapper qui va géré le DL au `globalSetup`.

chore: suppression du test coverage & utilise de jest-mongodb

---

jest.config.js

Problème de format de testMatch dans la conf Jest spécifique à Windows 🪟 
Cf : https://github.com/jestjs/jest/issues/7914#issuecomment-464352069

fix(tests): correction du format des match jestConfig

---

ui/modules/organismes/ListeOrganismesPage.tsx

Vu avec @nadinelouchart décision de masquer les organismes fermés ou absents du référentiel et inconnus. 
A voir si on les supprime ? Si on contacte les OF qui transmettent ? Autre ?

feat(ui): masquer les organismes fermés ou absents du référentiel et inconnus

---

.infra/docker-compose.production.yml
.infra/docker-compose.recette.yml

**Changements:**
Lors du restart d'un conteneur, on laisse 6 minutes au conteneur pour compléter le restart et éviter d'entrer dans une loop infini de restart. De plus on on limite à 240 attempts (24 heures).

chore: fix restart policy

---

server/src/common/actions/organismes/organismes.actions.ts
ui/modules/auth/inscription/components/SearchBySIRETForm.tsx
ui/modules/auth/inscription/components/SearchByUAIForm.tsx
ui/pages/auth/inscription/organisme-inconnu.tsx

Comme vu à l'IRL (au moins avec Nadine et Antoine), on ne doit pas (plus) laisser s'inscrire des utilisateurs OFA dont l'organisme n'est pas dans le référentiel.
Jusque-là (sans compter l'expiration de la clé d'api entreprise...), on autorisait l'utilisateur avec un SIRET valide à créer un compte.

refactor: suppression inscription OF non présent dans le référentiel

---

server/src/commands.ts

Empêche le serveur de dev de démarrer le processor, qui démarre tous les jobs du cron daily, tous les jours alors qu'on en veut pas.

chore: supprime les crons pour l'env de dev

---

server/src/common/actions/sifa.actions/sifa.actions.ts

Parce qu'on la demande dans l'API v3 sous ce format de manière obligatoire

fix: pour sifa on prend la date de duree theorique si on la trouve dans l'effectif

---

server/src/common/actions/organisations.actions.ts
server/src/common/actions/organismes/organismes.actions.ts
ui/modules/mon-espace/effectifs/ChoixERP.tsx
ui/modules/mon-espace/effectifs/ChoixTransmission.tsx
ui/modules/mon-espace/effectifs/EffectifsPage.tsx

Remet en place le processus classique de configuration de l'ERP, sauf pour SCForm qui redirige l'utilisateur vers la configuration de la clé d'API.
Les changements d'état de configuration ne fonctionnaient pas à cause des derniers changements sur les permissions qui ne renvoie pas toujours toutes les informations de l'organisme.
Il y a un atelier prévu demain après-midi pour repenser le workflow de configuration ERP.

fix: corrections configuration erp + scform (clé d'api)

---

server/src/common/actions/organismes/organismes.actions.ts

A la confirmation de configuration de clé d'API à l'URL `/connexion-api?siret=XXXXX&uai=YYYYY&erp=ZZZZ&api_key=TTTTT`, l'ERP est enregistré et ajouté dans la liste des ERP de l'organisme.

feat: sauvegarde de l'ERP à la connexion API

---

server/tests/data/sampleEtablissements.ts

Idéalement, il faudrait supprimer tout random des tests pour être sûr de ce qu'on teste.

fix: correction d'un test flaky (mauvais siret)

---

server/src/common/actions/organismes/organismes.actions.ts
server/src/http/server.ts

Comme dit en IRL, seul le référentiel compte, et on ne doit pas chercher d'info via l'API entreprise.
Cependant, il y a plusieurs appels un peu partout, alors je propose de détricoter au fur et à mesure.
Première étape qui me parait pas trop risquée, faire sauter `getOrganismeByUAIAndSIRETOrFallbackAPIEntreprise` (et ses dépendances) vu que le nom est suffisamment explicite.
@sbenfares et @totakoko je vous ai mis tous les deux en relecteurs comme c'est un sujet dont on a parlé tous les 3.

fix: suppression de la dépendance à l'api entreprise step 1

---

.talismanrc
server/src/common/actions/account.actions.ts
server/src/common/actions/helpers/permissions-organisme.ts
server/src/common/actions/helpers/permissions.ts
server/src/common/actions/organisations.actions.ts
server/src/common/actions/organismes/organismes.actions.ts
server/src/common/model/@types/Organisation.ts
server/src/common/model/organisations.model.ts
server/src/common/validation/registrationSchema.ts
server/src/db/migrations/20230320000001-create-organisations.ts
server/src/db/migrations/20230921000000-simplify-organisations-ofa.ts
server/src/jobs/seed/start/index.ts
server/tests/integration/http/organisme.routes.test.ts
server/tests/utils/permissions.ts
ui/common/internal/Organisation.ts
ui/components/Page/components/NavigationMenu.tsx
ui/modules/auth/inscription/common.ts
ui/modules/auth/inscription/components/SearchBySIRETForm.tsx
ui/modules/auth/inscription/components/SearchByUAIForm.tsx
ui/modules/dashboard/DashboardOrganisme.tsx
ui/modules/indicateurs/IndicateursForm.tsx
ui/modules/indicateurs/permissions-onglet-graphique.ts
ui/modules/organismes/ListeOrganismesPage.tsx
ui/pages/auth/inscription/profil.tsx
ui/pages/connexion-api.tsx
ui/pages/enquete-sifa.tsx
ui/pages/index.tsx
ui/pages/organismes/[organismeId]/enquete-sifa.tsx

En gros :
type: z.enum([
"ORGANISME_FORMATION_FORMATEUR",
"ORGANISME_FORMATION_RESPONSABLE",
"ORGANISME_FORMATION_RESPONSABLE_FORMATEUR",
]),
=>
type: z.literal("ORGANISME_FORMATION")
Car cette distinction initialement basée sur la nature de l'organisme n'est pas utilisée. La nature n'est même pas à prendre en compte car il faut regarder les organismes formateurs pour connaître le type de relation...

refactor: simplifications des organisations OFA

---

server/src/common/validation/utils/zodPrimitives.ts
server/tests/integration/jobs/ingestion/process-ingestion.test.ts

On a eu des gens qui ont envoyé des sirets formatés avec des espaces et des points dans le téléversement. Ça ne sert à rien de les embêter avec ça.

fix: accepter les espaces, tirets et points et les supprimer silencieusement dans les siret

---

.infra/docker-compose.preview-system.yml
.infra/docker-compose.recette.yml

La PR #3233 n'a pas suffit. Il manquerait une configuration côté mailpit pour bien gérer le préfixe (sans slash). On pourrait sans doute s'en sortir avec que nginx, mais on ne va pas faire 150 essais / erreurs :upside_down_face:

fix: tente de corriger mailpit avec chemin /smtp

---

server/src/common/apis/apiDeca.ts

Vu avec @felixat13  et @camille (pas sur GH ?) 👉🏼 afin d'analyser les données DECA différentes entre TdB et Lba j'ajoute un log des appels avec les métadonnées reçues pour comparaison avec les métadonnées de LBA.

feat(server): ajout de log lors de l'appel à l'API Deca

---

ui/modules/organismes/Televersement.tsx

C'était en YYYY-MM-DD et un client a dit "au secours les dates sont inversées il y a un bug".
C'est plus joli en français (même si dans le fond on a un format pas très lisible (et yyyy-mm-dd c'est mieux) mais moins pire que l'infect mm/dd/yyyy qui est une abomination)

fix: affichage de la date en format français dans le rapport d'import excel

---

server/src/common/actions/sifa.actions/sifa.actions.ts
server/src/common/model/@types/Effectif.ts
server/src/common/model/effectifs.model/parts/formation.effectif.part.ts
server/src/common/model/effectifsQueue.model.ts
server/src/http/routes/specific.routes/effectif.routes.ts
ui/modules/mon-espace/effectifs/engine/cerfaForm/blocks/formation/EffectifFormation.tsx
ui/modules/mon-espace/effectifs/engine/cerfaForm/blocks/formation/formationSchema.ts

Ça touche à plusieurs choses en même temps, désolé (mais c'est difficile comme je détricote) : 
- Suppression de champs inutiles (non renseignées en prod)
- date_debut_formation
- date_fin_formation
- date_debut
- Enregistrement des champs date quand ils sont édités côté front
- Ajouts de nouveaux champs dans le bloc "formation"

fix: amélioration du formulaire effectif et de sifa

---

server/src/jobs/migrations/migrations.ts

- arrange le nom des variables _db => db
- supprime le paramètre client qui n'est jamais utilisé
- supprime la migration down qui n'est jamais utilisée

chore: maj variables nouvelles migrations

---

server/src/common/validation/utils/zodPrimitives.ts

Voir: https://mission-apprentissage.slack.com/archives/C02FR2L1VB8/p1695803791717199

fix: les UAI sont passés en majuscule lors de l'import (api toutes versions)

---

server/src/common/validation/utils/zodPrimitives.ts

Dans la doc on dit qu'on accepte F, M, H, 1 et 2 alors on va faire ça (dans la base on n'accepte que deux valeurs)

fix: le champ sexe échouait silencieusement dans l'import excel à cause du modèle

---

server/src/common/actions/organismes/organismes.actions.ts
server/src/common/validation/dossierApprenantSchemaV3.ts
server/src/http/server.ts

On vérifie que l'UAI et le siret sont valides (c'est à dire qu'ils sont présents dans la plateforme).
Je suis moyennement content de mon approche MAIS je la trouve pas mal quand même, parce qu'il faut que ça fonctionne avec Zod et que ça souligne au bon endroit.
En gros la limite, c'est que ça ne valide pas le couple UAI siret, mais chacun indépendamment. Mais ça permet d'avoir les erreurs bien affichées au bon endroit.
Et surtout les problèmes qu'on a actuellement, ce n'est pas du tout sur le couple mais sur des erreurs de fautes de frappes.
J'ai fait à la va-vite parce que j'ai ZERO temps aujourd'hui 😭 😭 😭

fix: vérification de l'UAI et siret dès la validation de l'import excel

---

ui/pages/admin/users/index.tsx

Et merde, il y a un accent dans la branche. Je crois que ça ne pose pas problème, mais github me le signale.

fix: afficher jamais connecté sur les utilisateurs plutôt que invalid date

---

server/src/commands.ts
server/src/common/actions/indicateurs/indicateurs.actions.ts
server/src/common/actions/indicateurs/indicateurs.ts
server/src/common/actions/rncp.actions.ts
server/src/common/model/@types/Rncp.ts
server/src/common/model/rncp.model.ts
server/src/http/server.ts
server/src/jobs/hydrate/hydrate-rncp.ts
server/src/jobs/jobs.ts
server/tests/integration/http/indicateurs.route.test.ts
server/tests/integration/http/organisme.routes.test.ts
server/tests/integration/http/rncp.routes.test.ts
ui/modules/dashboard/DashboardOrganisme.tsx
ui/modules/indicateurs/filters/FiltreFormationNiveau.tsx
ui/modules/models/indicateurs.ts
ui/modules/organismes/IndicateursEffectifsParFormationTable.tsx

- Sur le dashboard d'un organisme, nouvelle section quand il y a des effectifs avec un tableau des effectifs par niveau et formation (RNCP)
- Maj du job RNCP pour ajouter plus d'informations. car c'est utilisé pour afficher le libellé pour un code RNCP notamment.
~Va rester en preview en attendant des feedbacks.~
En fonction des retours, il faudra :

feat: affichage des effectifs par formation

---

ui/modules/organismes/OrganismesFilterPanel.tsx
ui/modules/organismes/filters/FiltreOrganismeUai.tsx
ui/modules/organismes/models/organismes-filters.ts
ui/modules/organismes/tabs/OrganismesACompleterPanelContent.tsx
ui/modules/organismes/tabs/OrganismesFiablesPanelContent.tsx

Vu avec @cathbaiona : ajout d'un filtre sur l'UAI connue ou inconnue sur la liste des organismes.
En attente décision produit @cathbaiona @nadinelouchart sur le fait que les admin seulement peuvent voir le filtre.

feat(ui): ajout du filtre UAI (connu ou inconnu)

---

server/src/common/actions/indicateurs/indicateurs-national.actions.ts
server/tests/integration/http/organisme.routes.test.ts
server/tests/utils/permissions.ts
ui/pages/index.tsx

cf: https://tableaudebord-apprentissage.atlassian.net/browse/TM-292

fix: changement des indicateurs nationaux pour les établissements tm-292

---

ui/common/httpClient.ts
ui/modules/indicateurs/filters/FiltreFormationSecteurProfessionnel.tsx

Suite à la nouvelle infra, les ports sont maintenant exposés. Or les requêtes sont toutes préfixées par l'URL du serveur.
Donc on va chercher explicitement le fichier sans préfixe serveur pour accéder à l'UI.
Pour tester avant / après, c'est sur la page Mes / Ses indicateurs en local.
Avant, erreur 404.
Après, le fichier est téléchargé.

fix: répare le lien vers l'arbo rome en local

---

.talismanrc
server/package.json
server/src/commands.ts
server/src/common/actions/organismes/organismes.actions.ts
server/src/common/model/@types/UsersMigration.ts
server/src/common/model/usersMigration.model.ts
server/src/common/services/mailer/mailer.ts
server/src/db/migrations/20231016000000-reset-organismes-transmission-date-no-effectif.ts
server/src/jobs/emails/reminder.ts
server/src/jobs/jobs.ts
server/static/emails/reminder_missing_configuration_and_data.mjml.ejs
server/static/emails/reminder_missing_data.mjml.ejs
server/tests/integration/jobs/emails/reminder.test.ts
server/tests/utils/testUtils.ts
yarn.lock

https://tableaudebord-apprentissage.atlassian.net/browse/TM-361
Description des changements :
- Ajoute un job pour envoyer les relances par email (utilisable directement avec `yarn cli send-reminder-emails`)
- Le job est configuré pour être exécuté dans un cron tous les jours à 7h du matin.
- 2 types de relances existent :
- un compte est créé, mais aucun mode de transmission n'a été configuré et aucun effectif n'est présent => email reminder_missing_configuration_and_data
- un compte est créé, un mode de transmission est configuré, mais aucun effectif n'est présent => email reminder_missing_data
- Chaque relance ne doit être faite qu'une seule fois, donc un état d'envoi est stocké pour chaque utilisateur pour chaque type de relance. J'ai notamment ajouté un test pour vérifier que tout …

feat : relances automatiques par emails si pas de données / configuration

---

server/src/db/migrations/20231025075713-remove-erps-value-objectId-in-organismes.ts

Ajout d'une migration qui supprime tous les champs ERPs de type ObjectId

feat(server): migration de suppression des objectId dans le champ ERPs des organismes

---

server/src/commands.ts
server/src/common/model/collections.ts
server/src/common/model/common.ts
server/src/common/model/rome.model.ts
server/src/jobs/hydrate/hydrate-rome.ts
server/src/jobs/jobs.ts

pour les analyses Metabase de @felixat13
Nouvelle commande / job :
- `hydrate:rome` : qui ajoute dans la collection `rome` les fiches métiers du [ROME](https://www.pole-emploi.org/opendata/repertoire-operationnel-des-meti.html?type=article) avec les labels des catégories parentes.
PS: J'ai utilisé zod pour gérer le schéma de validation mongo et les types TS (calqué sur les Jobs). On va sans doute pouvoir migrer petit à petit chaque collection...

feat: ajout collection ROME

---

server/tests/integration/common/actions/engine.organismes.utils.test.ts
server/tests/integration/http/dossiersApprenantsV2.route.test.ts
server/tests/integration/http/effectif.routes.test.ts
server/tests/integration/jobs/hydrate/hydrate-deca.test.ts
server/tests/integration/jobs/ingestion/process-ingestion.test.ts

Permet de passer de
à
en cas d'erreur d'un appel asynchrone dont on vérifie le résultat.

test: utilisation expect(...).resolves pour les promesses

---

.eslintrc.cjs
server/src/common/actions/helpers/filters.ts
server/src/common/actions/helpers/permissions-organisme.ts
server/src/common/actions/organismes/organismes.actions.ts
server/src/common/model/@types/index.ts
server/src/common/model/organismes.model.ts
server/src/http/helpers/passport-handlers.ts
server/src/http/middlewares/requireJwtAuthentication.ts
server/src/http/routes/admin.routes/users.routes.ts
server/src/jobs/ingestion/process-ingestion.ts
server/src/jobs/seed/types/generate-types.ts
server/tests/integration/http/organisme.routes.test.ts
server/tests/integration/http/referentiel.route.test.ts
server/tests/integration/http/rncp.routes.test.ts
ui/components/Page/components/Header.tsx
ui/components/withAuth.tsx
ui/hooks/useAuth.ts
ui/modules/admin/userSchema.ts
ui/modules/auth/inscription/InscriptionOperateurPublic.tsx
ui/modules/auth/inscription/components/OrganismeDetails.tsx
ui/modules/models/indicateurs.ts
ui/modules/mon-espace/SIFA/SIFAPage.tsx
ui/modules/mon-espace/organisation/InvitationForm.tsx
ui/pages/auth/modifier-mot-de-passe.tsx
ui/pages/index.tsx

- ajoute une règle ESLint qui détecte les FIXME et déclenche une erreur : ceci permettra d'utiliser `// FIXME blabla` pendant le développement d'une PR et d'être contraint d'y repasser avant de la donner à review.
- supprime les fixme existants ou les transforme en TODO (= idées d'amélioration)
- bonus (un peu important aussi _(sécu)_ ) : corrige une projection à faire dans la recherche d'organisme qui fuitait toutes les infos sur un organisme (dont les clés d'API v3, nb effectifs, etc).

refactor: nouvelle règle ESLint sur les FIXME

---

ui/modules/organismes/BandeauTransmission.tsx

Il faut indiquer la date la plus récente à gauche pour avoir une différence positive. (c'est le cas ailleurs dans les relances)

fix: condition sur le bandeau de transmission

---

server/src/common/validation/utils/zodPrimitives.ts

Suite à une remontée utilisateur. On est maintenant plus robuste sur ce champ.
Ça vaudrait peut-être le coup de généraliser ça à d'autres champs ? (ou pas...) @rap2hpoutre

fix: omission des espaces dans l'année scolaire

---

ui/modules/organismes/ListeOrganismesPage.tsx

Vu avec @nadinelouchart reorganisation des onglets : on mets dans l'onglet 3 les organismes fermés ne transmettant plus + les organismes inconnus.

feat(ui): déplacement des of inconnus dans onglets non retenus

---

server/src/common/model/@types/Effectif.ts
server/src/common/model/@types/Rncp.ts
server/src/common/model/effectifs.model/effectifs.model.ts
server/src/common/model/rncp.model.ts
server/src/jobs/hydrate/effectifs/hydrate-effectifs-computed.ts
server/src/jobs/hydrate/hydrate-organismes-opcos.ts
server/src/jobs/hydrate/hydrate-rncp.ts

Contenu :
- Modifie le job hydrate:rncp pour ajouter le champ opcos en provenant des 2 fichiers CSV OPCOs
- Modifie le job hydrate:effectifs-computed pour ajouter le champ _computed.formation.opcos avec les informations présentes dans la collection rncp
- Ajout d'indexes sur les champs car ils seront utilisés pour du filtrage, par @felixat13 dans un premier temps.
Note : readJsonFromCsvFile lit les fichiers de manière synchrone. Ce n'est pas grave ici étant donné qu'on est dans un job et pas dans le serveur web, mais c'est pas génial non plus.

feat: ajout rncp.opcos et effectifs computed opcos

---

server/src/common/actions/organismes/organismes.duplicates.actions.ts
ui/modules/dashboard/DashboardTransverse.tsx
ui/pages/admin/fusion-organismes/index.tsx

Problème de performances sur la feature de fusion : jointure nbUsers sur les organismes duplicates qui pose pb.
Temporairement je désactive la feature et je corrigerais lundi.

fix(ui): hide dashboard duplicate

---

ui/modules/organismes/Televersement.tsx
ui/modules/organismes/headerTooltips.tsx

https://tableaudebord-apprentissage.atlassian.net/browse/TM-350
https://www.notion.so/mission-apprentissage/Tests-t-l-versement-V2-am-liorations-du-front-cf94f348b36440358ed0211c9efcb5c8?pvs=4#84f6455bf6ba42fe833bffbd623a31a4

feat: tooltips sur les headers

---

server/src/common/actions/effectifs.actions.ts
server/src/common/actions/indicateurs/indicateurs.actions.ts
server/src/common/model/effectifs.model/effectifs.model.ts
server/src/jobs/hydrate/effectifs/hydrate-effectifs-computed.ts
server/tests/integration/http/organisme.routes.test.ts
server/tests/utils/permissions.ts

Vu avec @nadinelouchart on masque les effectifs lié à des OF "inconnus".
- Ajout dans le champ computed des effectifs de la raison sociale et de l'enseigne
- Ajout dans le filtre des requêtes d'un filtrage sur ces 2 champs

feat(server): masquer les effectifs d'OF dont on ne connait pas la raison sociale ou l'enseigne

---

server/src/common/actions/effectifs.actions.ts
server/src/common/actions/indicateurs/indicateurs.actions.ts
server/src/common/model/effectifs.model/effectifs.model.ts
server/src/jobs/hydrate/effectifs/hydrate-effectifs-computed.ts
server/tests/integration/http/organisme.routes.test.ts
server/tests/utils/permissions.ts

This reverts commit 8e5d16df61431e2b7dd9cb2d1e16de9f63b6f261.
Vu avec nadine, on perds trop d'apprenants, on revient en arrière et on prendra une décision produit.

Revert "feat(server): masquer les effectifs d'OF dont on ne connait pas la raison sociale ou l'enseigne (#3356)"

---

.talismanrc
server/src/common/validation/utils/zodPrimitives.ts
server/static/open-api.json
server/tests/integration/jobs/ingestion/process-ingestion.test.ts

Vu avec Nadine et Catherine, l'idée est de ne permettre que les années calendaires ou scolaire et de bloquer les personnes qui mettent: 2023-2025 (2 ans)

fix: contrôle précis (v2v3+televersement) sur les années scolaire pour accepter seulement un an max

---

server/src/common/actions/users.actions.ts
ui/common/constants/usersConstants.ts
ui/common/internal/Organisation.ts
ui/common/internal/User.ts
ui/components/FilterButton/FilterButton.tsx
ui/hooks/users.ts
ui/modules/admin/users/UsersFiltersPanel.tsx
ui/modules/admin/users/filters/FiltreUsersAccountStatut.tsx
ui/modules/admin/users/filters/FiltreUsersDepartements.tsx
ui/modules/admin/users/filters/FiltreUsersRegion.tsx
ui/modules/admin/users/filters/FiltreUsersReseaux.tsx
ui/modules/admin/users/filters/FiltreUsersType.tsx
ui/modules/admin/users/models/users-filters.ts
ui/modules/admin/users/models/users.ts
ui/modules/organismes/filters/FiltreOrganismeDepartements.tsx
ui/modules/organismes/filters/FiltreOrganismeEtat.tsx
ui/modules/organismes/filters/FiltreOrganismeNature.tsx
ui/modules/organismes/filters/FiltreOrganismeRegions.tsx
ui/modules/organismes/filters/FiltreOrganismeTransmission.tsx
ui/modules/organismes/filters/FiltreOrganismeUai.tsx
ui/modules/organismes/filters/FiltreYesNo.tsx
ui/pages/admin/users/index.tsx

Ajout de filtres sur la page utilisateurs (admin)
Cf : https://tableaudebord-apprentissage.atlassian.net/browse/TM-440
Maquette : https://tableaudebord-apprentissage.atlassian.net/browse/TM-440
- J'ai un peu refacto le code (avec des hooks)
- Ajout des données utiles pour les filtres coté serveur (adresse -> région & dpt)
- Création d'un type UsersPaginated pour la récupération coté API des données paginées
- J'ai repris la logique des filtres organismes / indicateurs
Il manque le filtre périodes car il n'a pas été spécifié pour l'instant, on verra dans un prochain sprint.

feat: ajout des filtres sur la liste des utilisateurs

---

ui/common/internal/User.ts
ui/modules/admin/users/models/users-filters.ts
ui/modules/admin/users/models/users.ts

2 petites anomalies sur les filtres utilisateurs : 
- J'avais oublié de filtrer sur le dpt / région de l'organisation quand il y en a
- Pb de format de date
Cf https://tableaudebord-apprentissage.atlassian.net/browse/TM-501

fix(ui): filtres région / dpt sur organisation + format date

---

server/src/db/migrations/20231128113006-delete-effectifs-computed-organisme-raisonSociale-enseigne.ts

Une ancienne PR ajoutait au champ _computed des organismes la raison sociale et l'enseigne 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/3356
Finalement on est revenus en arrière 👉🏼 https://github.com/mission-apprentissage/flux-retour-cfas/pull/3361 en supprimant ces champs du modèle mais on a pas fait de revert des données.

feat(server): migration de suppression de la raisonSociale - enseigne computed dans effectifs

---

ui/common/exports.ts

Ce n'étais pas clair, mais j'ai constaté que deux variables étaient en fait des années (bizarre d'ailleurs mais bon) alors que dans l'export je pensais que c'était des dates.
```
formation_date_debut_formation: { $arrayElemAt: ["$formation.periode", 0] },
formation_date_fin_formation: { $arrayElemAt: ["$formation.periode", 1] },
```
Donc j'ai corrigé. (https://tableaudebord-apprentissage.atlassian.net/browse/TM-516)

fix: dates de début-fin de formations en années dans l'export nominatif il ne faut pas le formater

---

server/src/common/actions/sifa.actions/sifa.actions.ts

cf: https://tableaudebord-apprentissage.atlassian.net/browse/TM-554
L'apprenant avait ces status (voir les dates) : 
```
[
{
"valeur_statut": 2,
"date_statut": {
"$date": "2023-09-25T00:00:00.000Z"
},
"date_reception": {
"$date": "2023-10-18T13:53:48.645Z"
}
},
{
"valeur_statut": 3,
"date_statut": {
"$date": "2023-09-25T00:00:00.000Z"
},
"date_reception": {
"$date": "2023-11-22T10:29:11.371Z"
}
}
]
```

fix: apprenant avec deux dates de statuts identiques (apprenti+inscrit) pas pris en compte dans SIFA

---

server/src/common/actions/organismes/organismes.actions.ts
server/src/common/model/@types/Organisme.ts
server/src/common/model/organismes.model.ts
server/src/http/routes/admin.routes/organismes.routes.ts
server/src/jobs/ingestion/process-ingestion.ts
ui/modules/admin/InfosTransmissionEtParametrageOFA.tsx

Ajout de l'information de l'OF transmetteur dans la collection organismes puis dans l'encart admin.
Testé en local mais je n'ai pas fait de migration, le champ va se remplir "tout seul" au fil de l'eau de l'ingestion.

feat: ajout de l'organisme transmetteur dans l'encart admin

---

server/src/common/actions/effectifs.actions.ts

Pour reproduire : modification de statut ou de contrat génère une erreur 500

fix: la modif de l'historique de statut ou de contrat générait parfois un crash (+ non sauvegarde)

---

server/src/common/actions/helpers/permissions-organisme.ts
server/tests/integration/http/organisme.routes.test.ts

Update des droits de téléchargement des listes nominatives cf. https://tableaudebord-apprentissage.atlassian.net/browse/TM-422

feat(server): download DREETS / DRAAF uniquement des rupturants

---

server/src/common/actions/helpers/permissions-organisme.ts
server/tests/integration/http/organisme.routes.test.ts

MAJ des droits de téléchargements des listes nominatives (la carte n'était pas à jour) cf https://tableaudebord-apprentissage.atlassian.net/browse/TM-422

feat(server): update droits téléchargement listes nominatives

---

.talismanrc
server/src/common/actions/effectifs.actions.ts
server/src/common/utils/mergeIgnoringNullPreferringNewArray.ts
server/src/jobs/ingestion/process-ingestion.ts
server/tests/integration/common/utils/mergeIgnoringNullPreferringNewArray.test.ts
server/tests/integration/jobs/ingestion/mergeEffectif.test.ts

J'ai essayé de bien commenter.
À chaque ingestion d'effectif : 
AVANT : on remplaçait totalement l'effectif
MAINTENANT : on fusionne avec l'effectif existant
https://mission-apprentissage.slack.com/archives/C02FR2L1VB8/p1702376081971259

feat: les effectifs envoyés sont fusionnés pour éviter d'effacer les valeurs ajoutées manuellement

---

server/src/common/actions/effectifs.actions.ts
server/src/jobs/ingestion/process-ingestion.ts

Bizarrement, la modif de [ce commit](https://github.com/mission-apprentissage/flux-retour-cfas/pull/3404/files) n'était pas suffisante parce qu'il y avait une sorte de forçage sur trois champs que je dois skip
Bonus: j'ai supprimé une fonction inutilisée. J'évite tant que possible de mélanger deux sujets dans une PR, mais là c'était compliqué car je faisait évoluer une fonction qui était utilisée par une fonction non-utilisée.

fix: on autorise la modif nom/prénom/cfd des effectifs téléversés (qui étaient verrouillés de force)

---

server/src/common/actions/helpers/permissions-organisation.ts
server/src/common/actions/helpers/permissions-organisme.ts
ui/pages/organismes/[organismeId]/enquete-sifa.tsx

Deuxième partie du ticket https://tableaudebord-apprentissage.atlassian.net/browse/TM-438

feat: tete de réseau compagnon du devoir peut gérer les effectifs et l'enquete SIFA

---

server/src/jobs/emails/reminder.ts
server/tests/integration/jobs/emails/reminder.test.ts

[TM-601](https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/TM/boards/1/backlog?selectedIssue=TM-601)
Mise en pause du service de relance par e-mail pour les organismes configurés mais qui n’ont pas de donnée.

fix: mise en stand-by des e-mails de relance

---

server/src/common/actions/organismes/organismes.duplicates.actions.ts
ui/modules/admin/fusion-organismes/OrganismesDoublonsList.tsx
ui/modules/admin/fusion-organismes/models/DuplicateOrganismeDetail.ts

[TM-590](https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/TM/boards/1/backlog?assignee=712020%3Aa35d39f1-286a-43a4-8ad3-c1041b95d2a1&atlOrigin=eyJwIjoiaiIsImkiOiJlOGFiZTQ2MjYyZGQ0YmIzYTkxNmQwN2ExMDIxYzI4NyJ9&cloudId=fd0b3ea4-845f-441e-bce3-72c8a7dbd0a3&selectedIssue=TM-590)
**Description :**
Cette Pull Request vise à optimiser l'affichage de la liste des doublons d'organismes en mettant en priorité l'affichage des informations selon l'ordre suivant : la raison sociale, ensuite l'enseigne, et enfin le nom de l'organisme. Cette modification permet une identification plus précise et une meilleure compréhension des données pour les utilisateurs.
**Détails des changements :**
Modification du composant RenderSubComponent dans le fichier OrganismesDoublonsList.tsx pour …

Amélioration de l'affichage des noms des doublons d'organismes

---

server/src/http/routes/specific.routes/organisme.routes.ts
ui/modules/effectifs/EffectifsPage.tsx

cf : https://tableaudebord-apprentissage.atlassian.net/browse/TM-571
J'ai mis la même liste (les mêmes données/colonnes) que celle des indicateurs, à avoir s'il y a besoin d'adapter plus tard. On reprend la liste des effectifs affichés et on permet de l'exporter

feat: pouvoir télécharger la liste nominative depuis la page effectif

---

shared/constants/plausible-goals.ts
ui/modules/mon-espace/SIFA/SIFAPage.tsx

cf: [TM-623](https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/TM/boards/1/backlog?assignee=712020%3Aa35d39f1-286a-43a4-8ad3-c1041b95d2a1&atlOrigin=eyJwIjoiaiIsImkiOiJlOGFiZTQ2MjYyZGQ0YmIzYTkxNmQwN2ExMDIxYzI4NyJ9&cloudId=fd0b3ea4-845f-441e-bce3-72c8a7dbd0a3&selectedIssue=TM-623)
Ajout des événement de tracking de la page SIFA suivant : 
Nom événement | Action à tracker | Propriétés associées | Emplacement de l’action | Statut tracking
-- | -- | -- | -- | --
clic_toggle_sifa_données_manquantes | clic sur le toggle afficher les données manquantes |   | page sifa  | to do
téléchargement_fichier_instruction_sifa | téléchargement du fichier d’instruction sifa |   | page sifa | to do
clic_depot_plateforme_sifa | clic sur le lien vers le dépot sur la plateforme sifa | …

feat: Ajout du tracking Plausible SIFA

---

server/src/common/actions/organismes/organismes.actions.ts
server/src/http/middlewares/requireBearerAuthentication.ts
server/src/http/server.ts

cf : [TM-612](https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/TM/boards/1/backlog?assignee=712020%3Aa35d39f1-286a-43a4-8ad3-c1041b95d2a1&atlOrigin=eyJwIjoiaiIsImkiOiJlOGFiZTQ2MjYyZGQ0YmIzYTkxNmQwN2ExMDIxYzI4NyJ9&cloudId=fd0b3ea4-845f-441e-bce3-72c8a7dbd0a3&selectedIssue=TM-612)
**Description :**
Cette Pull Request vise à optimiser la gestion des messages d'erreur en les ajustant à des codes 403 concernant à l'API key  lorsque celle-ci est incorrecte ou inexistante.
**Détails des changements :**
Remplacement des blocs de gestion d'exception existants par l'utilisation de la bibliothèque hapi.boom.
Modification des messages d'erreur pour les rendre plus explicites et en Français.
**Bénéfices attendus :**
Cette mise à jour vise à permettre aux ERP une meilleure …

fix: renvoyer une erreur 403 quand la clé API n'est pas bonne
